#+TITLE: Maven

* What is Maven

#+begin_quote
Apply patterns to a project's build infrastructure in order to promote
comprehension and productivity by providing a clear path in the use of best practices
#+end_quote

Essentially a project management and comprehension tool that manages

- Builds

- Documentation

- Reporting

- Dependencies

- SCMs

- Releases

- Distribution

* Archetype

An original pattern or model from which all other things of the same kind.
A template of a project which is combined with some user input to produce a
working Maven project.


* Quote Arguments under any Windows shell

* POM Outline

#+begin_src xml
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId></groupId>
  <artifactId></artifactId>
  <version></version>
  <name></name>

  <properties>
  </properties>

  <dependencies>
    <dependency>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
        </plugin>
    </pluginManagement>
  </build>
</project>
#+end_src

* [[https://maven.apache.org/plugins/index.html][Plugins]]

Maven is not a single monolithic build tool but a plugin execution framework: all work is done by plugins.

* Create Projects

use archetypes =mvn archetype:generate=, basically templates. Archetypes are additive in that another archetype can be added to an existing project.

* Build

- =mvn validate=: validate the project

- =mvn clean=: clean up artifacts generated by maven

- =mvn compile=: compiler plugin, compile source files

- =mvn test=: run the unit test code

- =mvn integration-test=: run the integration test code

- =mvn package=: take the source code and package into a distribution format

- =mvn verify=: verify the generated package

- =mvn install=: install the package into the local repository for other projects to use

- =mvn deploy=: deploy the package to a remote repository

- =mvn site=: generate a site documentation
