#+title: Lang Basics

- Constant expressions perform arithmetic with arbitrary precision;
  + a numeric constant has no type until it is specified or used in a context.

- =for= may act as =while= in Go, there is only one loop keyword in golang.
  + without any conditions as an infinite loop

- =if= may have an init statement before the condition
  and the variables declared in there are visible inside any of the =else= blocks.

- =break= is not required in =switch= clause
  + switch cases need not to be constants.
  + an init statement is allowed
  + switch without a condition is =switch true= and is used to write long
    =if-then-else= since cases need not to be constants.

    #+begin_src go
	switch {
	case t.Hour() < 12:
		fmt.Println("Good morning!")
	case t.Hour() < 17:
		fmt.Println("Good afternoon.")
	default:
		fmt.Println("Good evening.")
	}
    #+end_src

- =defer= statement defer the execution of a function until the containing
  function returns but evaluates the arguments on the spot.
  + pushed onto a stack; executed in a LIFO order

- *type embedding*: embedding of structs and interfaces to express a more
  seamless and automated composition of types, and also a way to implement inheritance.

  #+begin_src go
type base struct {
	num int
}

type container struct {
	base
	str string
}

co := container {
	base: base{
		num: 1,
	},
	str: "some time"
}

co.num // num can be accessed directly
co.str

co.base_method() // base methods can be used directly
  #+end_src

* How-to

** Formatted I/O

Use =fmt= package.

- one-based indexed argument is supported with =[n]= after =%=.

- =fmt.Sprintf= :: formatted string
