#+title: Basics

Cython is Python with C data types. Code which manipulates Python values and C
values can be freely intermixed. Refcount maintenance and error checking of
Python operations is automatic and Python error handling system is also available.

* Building

- =pyx= cython source files are first compiled to C source files and then built
  as a shared library.

- the library is then imported into a Python session.

- The most common way to build cython code is a setuptool =setup.py= (~python
  setup.py build_ext --inplace~); other ways
  include =cythonize=, =Pyximport= or jupyter notebooks.

* First Example

#+include: "./hello_world/setup.py" src python

* Static Typing

** Declarations

#+begin_src python
cdef int i, j, k
cdef float f, g[42], *h

cdef struct Grail:
	int age
    float volume

cdef union Food:
    char *spam
    float *eggs

cdef enum CheeseType:
    cheddar, edam,
    camembert

cdef enum CheeseState:
    hard = 1
    soft = 2
    runny = 3

ctypedef int* IntPtr


# a C function with a Python wrapper
cpdef long cfunc(long l):
	return 2 * l

#+end_src

** Functions

A pure Python function (take Python objects as parameters and return Python
 objects) is defined with =def= while a C function (take either Python objects
 or C values as parameters and can return either Python objects or C values) uses =cdef= or
is decorated with =@cython.cfunc=.

When a C type is declared as a parameter of a Python function, the passed value
is automatically converted to a C value (for numerica values only, otherwise a
compile-time error).

A parameter without typing is assumed to be a Python object and refcounted
automatically. =object= is used for explicit Python object declaration.

A function must be a Python function to be called from pure Python code.
=cpdef= or decoration =@ccall= defines a C function (using the faster C calling
convention) with a Python wrapper
and can be overriden by another Python function.

Both kinds of functions can be declared with a C-style declaration syntax, or
declared as type-annotated Python-style function with appropriate declarations.
