#+TITLE: Opc

https://www.codeproject.com/Articles/12441/OPC-Technology

* Why OPC

1. Standardized protocol

2. Reduced load on devices

3. Scalability

4. OPC provides caching

* OPC Classic

** Scope

The specification include a set of custom COM interfaces (and a set of OLE Automation interfaces) for use by client and server writers

1. Online Data Access (OPC DA): reading and writing o f data between an app and a process control device

2. Alarm and Event Handling (OPC A&E): the mechanisms for OPC clients to be notified of the occurrence of specified events and alarm conditions

3. Historical Data Access (OPC HDA): the reading, processing and editing of data of a historian engine

*** OPC Fundamentals

**** OPC DataAccess

- =OPCServer=: maintains information about the server and serves as a container for OPC group objects

- =OPCGroup=: a way for clients to logically orgainize data.
  + public OPCGroup: for sharing across multiple clients
  + local OPCGroup: local to a client

- =OPCItem=: connections to data sources within the server, must be in a group, no external interface.
  + a variant
  + contains a *Value*, *Quality* and *Time Stamp*


* Concepts and Terminology

- *OPC Server*: any server that provides OPC interfaces

- *OPC Address Space*: hierarchical

- *OPC Items/Tags*: leaf nodes, sensor attributes

- *folders, subfolders*: can map to some physical configuration or even geographical setup

- *OPC Group*: a set of OPC items: every client can create a logical entity called a group inside a OPC server. A client can maintain multiple groups. Every group has a unique name and has update rate, active flag, deadband, IO mode (sync/async), time bias(local time w.r.t GMT)

OPC provides sync and async reading and writing on hardware devices.

* COM Interfaces & Component Categories

=OPCEnum.exe=: a Windows Service that provides OPC server enumeration. The client application can query available OPC servers on local as well as remote networked machines.

Every OPC Server has to support the following interfaces

1. =IOPCBrowse=: browsing OPC Address Space.

2. =IOPCItemIO=: used for performing OPC Item read and write operations
