#+TITLE: Opcua Address Space

* Concepts

The primary objective of /AddressSpace/ is to provide a standard way for servers to represent /Objects/ to /Clients/. Objects and their metadata are represented as /Nodes/ and /NodeClasses/, described by /Attributes/ and interconnected by /References/. The set of /Objects/ and related inforamtion makes up the /AddressSpace/

** Node Model

- /Nodes/ are of their respective types, represented as /NodeClasses/.

- /Attributes/ are data elements that describe /Nodes/, included in the /NodeClass/ defintion.
  + Attribute has an /id/, a /name/, a /description/, a /data type/ and a mandatory/optional indicator.

- /References/ relate  a /SourceNode/ to a /TargetNode/, defined as instances of /ReferenceType/ /Nodes/. The Combination of /TargetNode/,  the /ReferenceType/ and the /TargetNode/ uniquely identify References. A /Reference/ can be a dangling /Reference/.

** Variables

Used to represent values, with the following two types:

*** DataVariables

Represents the content of an /Object/, e.g. an array of bytes, an aggregate of temperature values.

*** Properties

/Properties/ are Server-defined characteristics of /Objects/, /DataVariables/ and other /Nodes/. /Properties/ differ from /Attributes/ in that they characterise what the Node represents, such as a device or a purchase order. Attributes define additional metadata that is instantiated for all Nodes from a NodeClass. Attributes are common to all Nodes of a NodeClass and only defined by this specification whereas Properties can be Server-defined.

** TypeDefinitionNodes

OPC UA Servers provide type definitions for /Objects/ and /Variables/. An instance has a /HasTypeDefinition/ /Reference/ linked to its type definition. A complex /TypeDefinitionNode/ might reference other type defintions.

- /BaseObjectType/, /PropertyType/, /BaseDataVariableType/

*** Subtyping

/ObjectTypes/ and /VariableTypes/

** Event Model (Monitoring and Subscription Services)

Of /EventType/, represented as /ObjectTypes/

Events represent specific transient ocurrences. /Event Notifications/ reprot the occurrence of an /Event/. The /EventNotifier/ Attibute of certain nodes identifies if the Node allows subscribing to Events. Clients subscribes to nodes that allow subscribing to events to receive /Notifications/.

** Methods (Call Service)

Of the /Method/ NodeClass.

Similar to methods in OOP programming.

** Role

Security roles, based on which access permissions are granted to clients. Roles are determined based on

- user identity: user name, user certificates or user groups

- Application identity: client certificate

- Endpoint: the URL used to connect to the server.

There are some predefined well-known roles.
