A Mandatory Access Control framework for Linux,
which controls access to resources based on central policies,
instead of owners' /discretion/ (DAC).

SELinux conflicts with AppArmor if run simultaneously.

* Basics

** Terms & Concepts

A /subject/ requests access (controlled by *access vector rules*) to an object (from /object manager/);
/object manager/ (the Linux Security Modules) queries permissions from /security center/ (/access vector cache/ is tried first);
security center (in the kernel) makes decisions based on the security policy

- *Subject*: a subject requests access to take an action, typically a process, 

- *Object Manager*: controls the access of the subject.

- *Security Center*: makes decisions based on the security policy and returns an answer.

- *Access Vector Cache*:

- *Security Context*: each object or subject is assigned a security context
  to determine if a subject can access an object based on strict policy rules.
  + =user:role:type[:range]=
  + =ls -Z=j

- *SELinux user* (ending with =_u=): separated from Linux users.
  + a linux user is mapped to SELinux users.
	+ =seinfo -u= lists these users.
	+ =semanage login -l= lists user mappings.
		=__default__= is used if no other mapping exists for a Linux user.
		Or =/etc/selinux/SELINUXTYPE/seusers= 
		where =SELINUXTYPE= defines the current security policy structure.

- *SELinux role* (ending with =_r=)

- *type*: the type of a subject, domain or object decides its permissions.
  + what a subject can access; what access permissions a user has on an object 

- *range*: a range of sensitives.
  + *sensitivity* =sN= is an attribute of an object to enforce hierarchical data classification; 
	  a subject must have a clearance level that dominates the object's sensitivity level.
	+ *categories* =cN=: similar to senstivities but without hierarchies.

* Security Policies

There is a reference policy defined by the SELinux project, which is then customized by distributions.

Security policies are defined in special syntax (M4) in files and requires compilation.
To add a rule, write a =te= file and compile it (=make module_name.pp=
with the =Makefile= from =/usr/share/selinux/devel/Makefile=) and then install it (=semoduel -i=).

* The Linux Security Modules

* Troubleshooting

** SELinux Logs

=/var/log/audit= or =/var/log/audit/audit=.log

or =sealert= or =ausearch=

#+begin_src shel
ausearch -m AVC # search for AVC (denials)
#+end_src
