#+title: System Programming Concepts

* System Calls

The OS kernel provides service in the form of system calls. A system call
differs from a purely user-mode library call in that a context switch from
user mode to processor is required to branch to kernel code, typically initiated by a special CPU
instruction
while a normal library call simply requires a jump to a certain address in the
process's user-mode address space. Calling conventions, error handling are
relatively minor difference.

The kernel retrieves the syscall number as an index into the dispatch table to
find the corresponding handler's address, performs some check on the arguments
and calls the handler. The result and error number is returned to the user mode
wrapper to transform by another convention.

On Unixes, system calls are provided as wrapper functions in libc, unlike on
Windows NT, where system service calls are typically hidden behind the Win32
subsystem library functions and various other C library functions. POSIX
functions are not required to be system calls and may be implemented as user-mode library functions.

* Error Handling

Always check on returned status of any important function call.

- system calls typically returned a =-1= to indicate a failure and sets the
  global =errno= (a modifiable thread-local lvalue) to a positive value to identify the specific error.
  + =errno= is never reset to zero by function calls under any circumstances
    and may be set to positive values by successful calls. The result is
    undefined on success.
  + some syscalls even return =-1= on success then only an =errno= change from
    zero can detect any failures.
  + =errno= can be interpreted by =perror()= and =strerror*()=.
  + there is also a util program =errno= that describes an =errno=.

- library functions may act like system calls in terms of error status, with
  some deviations (returning other negative values on failure), or don't use
  =errno= at all.

* Portability Issues

** Feature Test Macros

[[man:feature_test_macros][feature test macros]]

A set of macros to define before including system headers to enable or disable certain features of libc.
A confusing name but makes sense from the library: the library tests these
macros to determine features available.

- =_POSIX_C_SOURCE= (defined by default) :: POSIX 1003.1 feature set
  + may disable BSD and SVID features unless they are explicitly defined

- =_XOPEN_SOURCE= :: SUS

- =_GNU_SOURCE= :: a combination of various feature sets including GNU-specific extensions.

- =_BSD_SOURCE=, =_SVID_SOURCE= :: BSD and SysV-derived definitions (deprecated,
  use =_DEFAULT_SOURCE=)

- =_DEFAULT_SOURCE= (defined by default unless some other macros are defined) :: POSIX.1, C99, BSD, SVID

Some macros may be defined with different values to enable different versions of
the feature set. These macros are not independent of each other and may
influence each other.

** System Data Types

[[man:system_data_types][System Data Types Manpage]]

SUS defines a few standard data types to represent system data structures
to improve portability.

To print such opaque types, try casting them to =long= or even =long long= and
use =%ld=, or use any other larger integer types.

** Other Issues

- struct member order is not defined by SUS.
