* Memory Management Overview
  :PROPERTIES:
  :CUSTOM_ID: memory-management-overview
  :END:

#+BEGIN_EXAMPLE
  +-----------------------------------------------------+
  |                                                     |
  |          Windows Program     C Library              |
  |                                                     |
  +-----------------------------------------------------+
   +----------------------------------------------------+
   |                         ||                         |
   |  Heap API: HeapCreate.. ||                         |
   |                         ||   MMF API:              |
   +--------------------------|     CreateFileMapping   |
   +--------------------------|     CreateViewOfFile    |
   |                         ||                         |
   |  Virtula Memory API     ||                         |
   |                         ||                         |
   +----------------------------------------------------+
   +----------------------------------------------------+
   |              Windows Kernel with                   |
   |              Virutal memory manager                |
   |                                                    |
   +--------|---------------------------------^---------+
            ^                                 |
            |                                 |
            |                                 |
   +--------v-----------+            +--------v---------+
   |                    |            |                  |
   |  Physical memory   |            | Disk & filesystem|
   |                    |            |                  |
   +--------------------+            +------------------+
#+END_EXAMPLE

#+BEGIN_SRC C
  VOID GetSystemInfo(LPSYSTEM_INFO lpSystemInfo)
#+END_SRC

* Heap
  :PROPERTIES:
  :CUSTOM_ID: heap
  :END:

Use C library to allocate heap memory
if one heap (process heap =GetProcessHeap()=) is sufficient.
Heaps are Windows objects (non-kernel objects): they have handles.
Heap separation has several benefits:

- multithread performance: each thread can have its own heap
- allocation efficiency and low fragmentation, simplifies
  synchronization
- deallocation efficiency: an entire heap can be freed with a single
  function call
- locality of reference efficiency, reducing page faults

Use =HeapCreate()= to create a new heap, specifying the initial heap size.
Heaps allocation always rounds up to a multiple of the page size.

Heaps are not kernel objects so they have no security attributes.
Destroy a heap with =HeapDestroy()=. Do not destroy the process heap.
Destroying a heap eleminate the need to write the data structure
traversal code and deallocate each individual code.

=HeapAlloc()=; =HeapFree()=; =HeapReAlloc()=; =HeapSize()= (which determines the
size of an allocated block)

* Memory Mapped Files
  :PROPERTIES:
  :CUSTOM_ID: memory-mapped-files
  :END:

Convenient and efficient in-memory algorithms can process file data even
though the file may be much larger than available physical memory. File
processing is frequently much faster than using File I/O. No need to
manage buffers. Multiple processes can share memory by mapping.

The OS itself uses memory mapping to implement DLLs and to laod and
execute executables.

Create a file mapping object with =CreateFileMapping=. Get a file
mapping handle with=OpenFileMapping=. Map a file with =MapViewOfFile()=
after getting the mapping handle. Close the mapping with
=UnmapViewOfFile()=. Flush the dirty pages with =FlushViewOfFile()=.

