#+title: DOS Programming

* Early x86 Machine
:PROPERTIES:
:ID:       4bb8c2cc-3730-469d-8f8f-31aa090a6069
:END:

** 8086 Architecture

*** 8086

- All internal registers and external/internal data buses are 16-bit

- 20-bit external address bus, with 16-bit multiplexed with the data bus.

- 16-bit I/O address bus

**** Registers

14 separater registers

***** General Purpose

- =AX=, =BX=, =CX=, =DX=: general purpose
  + =AL=, =AH= ...

***** Segment Registers

- =CS=: code segment

- =DS=: data segment

- =ES=: extra segment

- =SS=: stack segment

***** Offset Registers

To access the 20-bit address space, one register would not suffice.

- =BP=: (stack) base pointer; =SP=: stack pointer, used with =SS=

- =SI=: source (during data transfer) index, used with =DS=

- =DI=: destination (during data transfer) index, used with =ES=

- =IP=: instruction pointer, program counter, paired with =CS=

***** Flags Register

- =Flags=: status flags

*** 80286

- 24-bit address bus

- separate address/data buses

- On-chip MMU to support protected mode
  + transition from protected mode back to real mode requires a reset.

** Memory Model

- 20-bit address bus from =0x00000= to =0xFFFFF=
  + CPU after 8088 can access high memory called *extended memory*, often used
    for disk caches, RAM disks and print spoolers, which can be
    configured as *expanded memory* for programs to store data.


#+begin_src
┌─────────────────────────────────┐ FFFFF (1M)
│                                 │
│           BIOS                  │
├─────────────────────────────────┤ E0000
│                                 │
│                                 │
│        Reserved                 │
│                                 │
├─────────────────────────────────┤ A0000 (640K)
│  Transient COMMAND.COM          │
├─────────────────────────────────┤
│                                 │
│                                 │
│                                 │
│                                 │
│     Transient Program area      │
│        (user memory)            │
│                                 │
│                                 │
│                                 │
├─────────────────────────────────┤
│   Resident COMMAND.COM          │
├─────────────────────────────────┤
│          Buffers, Drivers       │
├─────────────────────────────────┤
│                                 │
│             DOS Kernel          │
│                                 │
├─────────────────────────────────┤
│             BIOS                │
├─────────────────────────────────┤ 00400
│           Interrupt             │
│         Vector Table            │
└─────────────────────────────────┘ 00000
#+end_src

*** Segmented Memory Addressing

Since a CPU register is 16-bit only, allowing only 64KB address,
the /segment register/ value is automatically multiplied by 16,
and thus able to access up to 1MB memory, 16 non-overlapping segments, or 64K
overlapping segments. Each 16-byte chunk is called a /paragraph/.

To access the memory in a fine
granular manner, the /offset register/ is added to the multiplied result,
normally written as:

#+begin_src
segment:offset
#+end_src

**** Pointers

- /near pointers/: 16-bit offsets

- /far pointers/: 32-bit segment:offset pairs resolving to 20-bit external addresses

- /huge pointers/: a linear 20-bit pointer.

** Interrupts

One of the main purposes of interrupts is to allow CPU to respond to external
events instead of busy waiting or occasion polling.

- 256 available interrupts numbered from =0x00= through =0xFF=.

*** Categories

- *internal interrupt* :: generated internally by the CPU when certain
  conditions or errors occur.

- *external hardware interrupt* :: generated by a peripheral hardware device.

- *software interrupt* :: generated by a program to gain access to system services.

* DOS Architecture
:PROPERTIES:
:ID:       0ee575a2-a7eb-4e8e-b962-c1a282d9e28d
:END:

- *BIOS* :: an interface to the hardware at boot time and run time
  + the console
  + a generic line printer
  + the auxiliary device (usually a serial port)
  + the computer clock
  + the boot disk device
  + provides some system services

- *DOS Kernel* :: =MSDOS.SYS=, providing system services accessed by means of a
  *software interrupt*.
  + filesystem management
  + memory management
  + character device I/O
  + time/date support
  + program management
  + provides system services through =INT 21H=

- *Command Processor* :: =COMMAND.COM= the shell
  + loaded at boot time
  + has three modules
    + *resident module*: remains loaded in the memory as long as the computer is
      turned on, processing =Ctrl-Break= and =Ctrl-C= and loading the transient
      module if not loaded.
    + *initialization module*: processing =AUTOEXEC.BAT=
    + *transient module*: loaded in the high end of /user/ memory, processing
      commands and executing them.
  + can be replaced

* DOS API Programming
:PROPERTIES:
:ID:       91dd13c3-9b3f-435a-a5ab-4c3c6c546865
:END:

Most calls to the DOS API are invoked using the =INT 21H= software interrupt
with a subfunction number in the =ah= register, basically a kernel syscall.

** Keyboard

Whenever a key is pressed or released, a scan code is generated and the 0x09
interrupt is generated. Normally, the BIOS is responsible for handling the
interrupt by setting some flags (e.g. =Ctrl=, =Alt=, =Shift=), generating
another interrupt (=Ctrl-Break=, =Ctrl-C= to Int 23H, =Alt-SysReq=), or set the keyboard buffer.

DOS kernel keyboard APIs are sensitive to input redirection (=stdin= and =stdout=).

*** =Ctrl-C=, =Ctrl-Break=

Upon pressing =Ctrl-C= or =Ctrl-Break=, DOS reads in and generates an =INT 23H=,
of which the default handler is to terminate the current process. DOS also
maintains a break flag, with the value of which being 0, DOS only checks for a
Ctrl-Break during certain I/O operations.

* BIOS Interrupt Call

The IBM PC BIOS sets up its interrupt handlers and provides basic hardware
control to the software running on the
machine, even though one may access hardware directly.

Modern OSes bypass any BIOS interrupt calls at all after startup due to real-mode
switch, limited memory address space, BIOS code performance issue, limited
functionality and compatibility issue of BIOS calls: a modern OS takes matters
in its own hands.


* DOS ABI

** Binary File Format

- *COM* :: CP/M =.COM=
  + no header, only code and data in a single segment, loaded at a preset
    address of offset 0x100 following the PSP.
  + maximum size of 0xFF00 bytes

- *MZ* :: DOS =.EXE=
  + supports multiple segments to be loaded at arbitrary memory addresses and
    executables greater than 64KB.
