* Terminology

- Primary Key: a unique, identifying value with which only one row is associated

- Foreign key: a link between two tables

- Composite/compound key: a key that refers to multiple columns

- Row/tuple/record/entry

* Basics

The user name in MariaDB is not a OS user name.
#+begin_src shell
mysql -u user_name -p -h host_name -P port_number
#+end_src

** User Management

*** Creation

1. =CREATE USER= creates a new row in =mysql.user=.

2. ='user_name'@'host_name': if the host name is not provided, it defaults to '%', or a domain name, or IP addresses, a range of IP addresses =base_IP/netmask=. The hostname has to be where the client connect comes from, a local nginx proxy counts as localhost.

** Getting Data

- =SELECT= statement
  + use =LIMIT= clause to limit the results
  + =WHERE=: selectivity. It is possible to do tuple comparison.
  + =ORDER BY=: order, goes after =WHERE= and before =LIMIT=
  + =DISTINCT=: distinctivity flag
  + =HIGH_PRIORITY=: flag, =SELECT= statement are considered to be of lower priority by default.
  + =SQL_CALC_FOUND_ROWS=: used with =FOUND_ROWS()=

#+begin_src sql
select
    name
from
    country_stats
inner join countries
    using (country_id)
where
    year = 2018 and
    (population, gdp) > (
        select
            avg(population),
            avg(gdp)
        from country_stats
        where year = 2018)
order by
    name;
#+end_src

- Common table expression (CTE)
  + Reference a result set multiple times in the same statement
  + Use a view without creating one
  + create a recursive query
  + simplify a complext query by breaking into multiple simple and logical building blocks

#+begin_src sql
with largest_economies as (
	select
		country_id, gdp
	from
		country_stats cs
	order by
		gdp desc
	limit 10
)
select
	name,
	gdp
from
	countries c
inner join largest_economies
	using (country_id);
#+end_src

- `INSERT`:

 #+begin_src sql
--- default insertion
insert into contacts(first_name, last_name, phone, contact_group)
values('Roberto','carlos','(408)-242-3845',default);

--- column specify out of order, specific to the mysql family
insert into contacts
set first_name = 'Jonathan',
    last_name = 'Van';
 #+end_src


* Minor Details

MariaDB is case-insensitive with regards to reserved words. Database and table names are case-sensitive on Linux as they reference the related directories and files on the filesystem.
