* Terminology

- Primary Key: a unique, identifying value with which only one row is associated

- Foreign key: a link between two tables

- Composite/compound key: a key that refers to multiple columns

- Row/tuple/record/entry

* Basics

The user name in MariaDB is not a OS user name.
#+begin_src shell
mysql -u user_name -p -h host_name -P port_number
#+end_src

** Initialization and Configuration

**** Setup

MariaDB needs the data in `mysql` database to manage prvileges, roles, plugins and help info. Use =mysql_install_db= to set up the database

#+begin_src shell
mysql_install_db --user=mysql --basedir=/path/to/basedir --datadir=/path/to/datadir
#+end_src

**** Use `systemd`

The service is started by `mysqld` not `mysqld_safe`. The startup script has a timeout, when the startup takes too long, systemd kills it. Use a template unit file `mariadb@` to start multiple instances.

https://mariadb.com/kb/en/systemd/#interacting-with-the-mariadb-server-process

** Schema Management

- =create/alter {database | schema }= options: character set, collation, comment. The DDL defintion can be shown using =show create database=

- =SHOW {DATABASES | SCHEMAS} [LIKE 'pattern' | WHERE expr]=: =information_schema.schemata=

** Character Set and Collations

- collation: the rules for comparing and sorting a particular set.A character set can have many collations associated with it, while each collation is only associated with one character set.

#+begin_src sql
SHOW CHRACTER SET; --- select * from information_schema.CHARACTER_SETS;
SHOW COLLATION; --- SELECT * from information_schema.COLLATIONS, ci (case-insenstive), cs (case sensitive)
SET NAMES { 'charset_name' | [COLLATE 'collation_name'] | DEFAULT } --- sets character_set_client, character_set_connection, chracter_set_results
SET {CHARACTER SET | CHARSET} {charset_name | DEFAULT} --- sets character_set_client, character_set_results, collcation_connection
#+end_src

Character sets and collations can be set from the server level right down to the column level, as well as for client-server communication.Character sets and collations always cascade down. By default, the character set and collation used for literals is determined by the =character_set_connection= and =collation_connection= system variables.

** Localization and Internationalization

MariaDB stores values internally in UTC, converting them to the required time zone as required.

- =lc-time_names=: sets the language used by the date and time functions =DAYTIME()=, =MONTHNAME()=, =DATE_FORMAT()=

- =lc_messages=: server error messages

- =time_zone=: the primary way to set the time zone

=default_time_zone= is an option in a server option group.

There are some functions and data types affected by the time zone settings.

#+begin_src sql
    NOW()
    SYSDATE()
    CURDATE()
    CURTIME()
    UNIX_TIMESTAMP()

    timestamp, datetime
#+end_src

** User Management

*** Creation

1. =CREATE USER= creates a new row in =mysql.user=.

2. ='user_name'@'host_name': if the host name is not provided, it defaults to '%', or a domain name, or IP addresses, a range of IP addresses =base_IP/netmask=. The hostname has to be where the client connect comes from, a local nginx proxy counts as localhost.


** Getting Data

- =SELECT= statement
  + use =LIMIT= clause to limit the results
  + =WHERE=: selectivity. It is possible to do tuple comparison.
  + =ORDER BY=: order, goes after =WHERE= and before =LIMIT=
  + =DISTINCT=: distinctivity flag
  + =HIGH_PRIORITY=: flag, =SELECT= statement are considered to be of lower priority by default.
  + =SQL_CALC_FOUND_ROWS=: used with =FOUND_ROWS()=

#+begin_src sql
select
    name
from
    country_stats
inner join countries
    using (country_id)
where
    year = 2018 and
    (population, gdp) > (
        select
            avg(population),
            avg(gdp)
        from country_stats
        where year = 2018)
order by
    name;
#+end_src

- Common table expression (CTE)
  + Reference a result set multiple times in the same statement
  + Use a view without creating one
  + create a recursive query
  + simplify a complext query by breaking into multiple simple and logical building blocks

#+begin_src sql
with largest_economies as (
	select
		country_id, gdp
	from
		country_stats cs
	order by
		gdp desc
	limit 10
)
select
	name,
	gdp
from
	countries c
inner join largest_economies
	using (country_id);
#+end_src

- `INSERT`:

 #+begin_src sql
--- default insertion
insert into contacts(first_name, last_name, phone, contact_group)
values('Roberto','carlos','(408)-242-3845',default);

--- column specify out of order, specific to the mysql family
insert into contacts
set first_name = 'Jonathan',
    last_name = 'Van';
 #+end_src

*** Temporary Table

Session-specific tables.

1. The privilege to =create temporary table= in a stored procedure is the creator's if the user does not have the privilege.

2. creating a temporary table does not cause an implicit commit.

** Some Useful Functions

#+begin_src sql
database(); --- the current database
schema(); -- your MySQL-ism
last_inserted_id();
now();
#+end_src

* Minor Details

MariaDB is case-insensitive with regards to reserved words. Database and table names are case-sensitive on Linux as they reference the related directories and files on the filesystem.
