#+TITLE: Mssql

# Configuration Tips

- The default install enables Windows authentication only, set the =LoginMode= registry key under =HKLM\Software\Microsoft\Microsoft SQL Server\ [instancename] \MSSqlServer= to =2= to enable mixed mode.

- New CLI client =mssql-cli=

DDL; DML (=SELECT=, =INSERT=, =UPDATE=, =DELETE=, =MERGE=, =TRUNCATE=); DCL (control): deals with permissions and includes =GRANT= and =REVOKE=

An element is identified by its key values, not by positions. A query against a table can return table rows in any order unless explicitly requested.

* Installation Caveats

- Run /System Configuration Checks/ before installation to check any prerequisite.

** Components

- Database Enginer :: a must

- Machine Learning Services :: as the name; optional

- Integration Services :: optional; integration with various data sources from XML, flat
  files to relational data without much coding.
  + from text, XML, Excel, relational databases
  + ADO, ADO.NET, EXCEL, file, FTP, HTTP, MSMQ, OLEDB, ODBC, SMTP, WMI, ORACLE etc.

- Analysis Services :: optional; decision support and business analytics
  + data models for Power BI; Excel, data visualization.

- Replication :: data synchronization between databases to maintain consistency.

- Data Quality Services :: optional; data cleansing, data matching, monitoring,
  knowledge base without coding.

- Master Data Services :: optional; master data; data organization, data modeling

** Editions

In addition to feature difference, different editions have different scale limits (CPU limits, memory usage limits)

- Standard: lesser of 4 sockets or 24 cores, 128 GB memory

- Enterprise: no limits

** Services

- Database Engine (=MSSQLSERVER=) :: =\<MSSQLPATH>\MSSQL\Binn\sqlservr.exe=

- SQL Server Agent (=SQLServerAgent=) :: =\<MSSQLPATH>\MSSQL\Binn\sqlagent.exe=
  + task automation (jobs), monitoring SQL Server

- SQL Server Browser :: name resolution service that provides SQL Server
  connection information for client computers

- SQL Writer :: backup and restore application in the Volume Shadow Copy Service
  framework (a Windows service)

** User Accounts

- installation requires a =sysadmin= role.

- the =sa= account (SQL Authentication) is also a database login and a member of =sysadmin=.

- The per-service service security principal (SID) is a login and a member of =sysadmin=.

** Multiple Instances

Installation of multiple instances on the same host is supported. No special
configuration except possible TCP port conflicts needs to be done.

SQL Server Browser and SQL Server VSS Writer are shared by all instances.
Database Engine, Analysis Services and Reporting Services are specific to an
instance. Some other components are shared by instances of the same major version.

An instance may be default or named. A named instance is identified by the
computer name plus the instance name. The instance name is required for clients
to connect to a named instance. A named instance has an /instance ID/ (by
default its name).

* Connections & protocols

** Concepts

- /Endpoint/ :: a connection on the server is represented by a T-SQL endpoint.
  + Permissions can be granted, revoked, and denied for Transact-SQL endpoints.
    By default, all users have permissions to access an endpoint unless the
    permissions are denied or revoked by a member of the sysadmin group or by
    the endpoint owner.
    + T-SQL local machine; T-SQL named pipes; T-SQL default TCP

** Configuration

By default, a SQL Server instance is configured for TCP/IP port 1433 and named
pipe =\\.\pipe\sql\query=. A named instance are configured for TCP dynamic ports
with a port assigned by the OS.


A client connects to the database with a /Login/ (instance-level authentication
object), possibly with a credential. A user (database-level authorization
principal) can be associated with a login.

* Backup and Restore

Use =BACKUP= to export a backup file. To =RESTORE= as another database, add
=WITH MOVE ... to ...=.
