Szegedy, C., Vanhoucke, V., Ioffe, S., Shlens, J., & Wojna, Z. (2016). Rethinking the Inception Architecture for Computer Vision. Proceedings of the IEEE Computer Society Conference on Computer Vision and Pattern Recognition, 2016-Decem, 2818–2826. https://doi.org/10.1109/CVPR.2016.308

* Background

1. The complexity of the Inception architecture makes it more difficult to make changes to the network.

2. There's no clear description about the contributing factors that lead to the various design decisions of the GoogLeNet.

* General Design Principles

1. avoid representational bottlenecks, especially early in the network. In general the representation
   size should gently decrease from the in- puts to the outputs before reaching the final represen- tation used for the task at hand.

2. Higher dimensional representations are easier to process locally within a network. 
  Increasing the activations per tile in a convolutional network allows for more disentangled features.
   The resulting networks will train faster.

3. Spatial aggregation can be done over lower dimensional embeddings without much or any loss in representational power.

4. Balance the width and depth of the network. Optimal performance of the network can be reached by balancing the number
   of filters per stage and the depth of the network.
