#+title: Bash Basics

* Features Particular to Bash

- =[[= conditional: regex matching, string pattern matching and logical operators =&&= and =||= without extra escapes

- shell arithmetic with one of the shell expansions or =let=

- =alias= and =unalias=: aliases are expanded upon a command/function is read.
  + usually not expanded by non-interactive shells.

- one-dimensional non-contiguous array variable declared by =declare=

- directory stack with =pushd=, =popd=, and =dirs=

- POSIX mode =set -o posix=, =--posix= or the envvar =POSIXLY_CORRECT= makes =bash= try to behave as compliant as possible
to the POSIX stnadard.

- restricted shell: certain operations and features are disallowed or disabled

* Startup Files

A shell may be a login shell or a non-login one and interactive or
non-interactive at the same time.

- Login Shells
  + =/etc/profile= the system login file
  + =~/.bash_profile=, =~/.bash_login=, =~/.profile=: the user login files. First readable file is read
  + =~/.bash_logout= upon logout
  + OpenSSH opens a non-login shell with a following command argument
  + =-bash= indicates a login shell.

- Interactive Non-Login Shells
  + =~/.bashrc= the environment file. A login shell may read this file inside =.profile=
  + It does not read =/etc/profile=, but usually it inherits a login shell.

- Non-Interactive Shell reads only =BASH_ENV= file
  + a shell may be non-interactive and login or non-login. So it may reads
    =/etc/profile= and others.

- As POSIX =sh=
  + login: =/etc/profile= + =~/.profile=
  + interactive: =$ENV=

* Interactive Shells

echo =$-= to check if the current shell is interactive (the result contains an
=i=).
An interactive shell has some features enabled:

- /job control/ enabled

- prompts =PS1= are set

- commands are read from the command line with =readline=

- the =ignoreeof= option is checked instead of exiting immediately upon EOF.

- /command history/ and /history expansion/ enabled

- /alias expansion/ enabled

- in the absence of traps, =SIGTERM= is ignored, =SIGINT= is caught and handled.

- =SIGHUP= to all jobs on exit is configured with =huponexit=.

- Redirection errors of built-in commands do not cause the shell to exit

- Failure of =exec= do not exit the shell.

- Parser syntax errors do not cause the shell to exit.

* Commands

** Classification

*** Builtin Commands

Contained within the shell itself.

- =cd -P=: cd to the physical path of the target, even if the target is a symlink.
  + by default =cd= follows symlinks instead of going to the actual directory.

- =eval=: take the input strings as a shell command
  + e.g. the output of certain commands can be =eval= to run.

- =export -p=  lists exported variables

- =hash=: shell caches commands' paths in a hashtable. This command manipulates the cache.
  + =-r=: flush the cache

- =readonly=: marks an exiting variable or creates a read-only variable

- =set= shell options, not variables.
   + =unset= does unset shell variables and functions.

- =trap=: installs signal handlers

- =getopts=: the command counterpart of [[man:getopt(3)][getopt]]

- =bind= (bashism): set key bindings

- =declare= (bashism): declare various variables, possibly with data types or cetain attributes..

- =let= (bashism): use =$((arithmetic_express))=

- =local= local variable, not POSIX but still portable in basically every shell.

- =printf=: C style output

POSIX-mode bash requires special builtins be found before shell functions during command
looup; if a special builtin returns an error status, a non-interactive shell
exits; variable assignments before a (special builtin ???) command stay in effect after the command completes.

TODO

*** Scripts

A new bash process is forked to execute a script. A script name as an argument
to =bash= is searched first in the current directory and then in the =PATH= variable.

*** Functions

Executed in the current shell context.

*** Other Programs

Executed in a new process.

** Execution Steps

Input is separated by /metacharacters/ and tokenized. Then alias expansion is
performed. Various shell expansions are then performed. Redirection is performed
if necessary. Variable assignments are saved. Commands are then executed and the
shell waits for them to complete.

*** Command Search

- search in the known function list

- search in the builtins

- search the =PATH=, cached in a hash table (=hash=).

- error 127 if not found

- executes the command in a separate execution environment; if the file is not
  executable and not a directory, it is assumed a shell script.

** Command History

- =fc=, =history= show history

- =fc -s event_number= reexecute the numbered command.

- =^R=, =^S= searches the history, for the next candidate, press =^R= or =^S= again.

* Shell Expansions

** Brace Expansion

#+begin_src shel
{a,b,c}1 # a1 b1 c1
#+end_src

Brace expansion is performed before any other expansions, and any characters special to other expansions are
preserved in the result.

** Tilde Expansion

=~TildePrefix= anything after a =~= and before =/=. Tilde expansion is more than =$HOME=. 

#+begin_src shell
~UserName # UserName's home directory

~ # $HOME

~+ # $PWD

~- #OLDPWD

~N+/- # up/down directory stack
#+end_src

** Parameter and Variable Expansion

Variables can be *global* (envrionment variables, exported variables, by convention UPPERCASE) 
or *shell*-local variables (by convention lowercase)

#+begin_src shell
${PARAMTER}

A=B
B=C
echo ${!A} # C indirect expansion

echo ${VAR:=value} # default value if undefined.
#+end_src

*** Common Useful Variables & Parameters.

- =CDPATH=: a searchpath for =cd= without full path

- =PWD= and =OLDPWD=

- =BASH_VERSION=, =BASH_VERSINFO=: bash version, the latter is an array of major, minor, patch, release/beta, arch.

- =LINES=, =COLUMNS=: current terminal height and width.

- =DIRSTACK=: an array containing the directory stack (list of recently visited directories.)

- =UID=, =EUID=: real and effective current user ID

- =FUNCNAME=: the currently executing function's name

- =LIENO=: the current line number of the script

- =MACHTYPE=: arch triplet

- =RANDOM=: a random number generator

- =$$=: current shell PID

- =$!=: recent background command PID

- =$@=: positional parameters, each parameter expands to a separate word when double quoted (peculiar but prefered to =$*=); 
  =$#= count of positional parameters

- =$?=: recent exit status

** Command Substitution

=$(command)= or =`command`= (old-style): performs the command and replace with the stdout of the command.

** Arithmetic Expansion 

=$((expression))=
Integer arimethic Only, useless. Use =bc= or =awk= for more complete arimethic.

All tokens in the expression undergo parameter expansion, command expansion and quote removal.

The expression is similar to that of C.

** Process Substitution (Bash, ksh, zsh, not POSIX)

A named pipe or a file under =/dev/fd/= is provided to a command as stdin or stdout.

- =>(command)=: =command= uses the file as input

- =<(command)=: =command= uses the file as output

The expansion returns the path to that file and another command may use the file
as input or output.

#+begin_src shell
while read line; do
      echo "$line"
done < <(grep "pattern" file.txt)
#+end_src

** Word Splitting

=$IFS= is used as a list of delimiters to split the output of other expansions into words.
By default the delimiters are space, tab and newline.

Note that quoted strings are not inherently an inseparable unit in Bash:
they are subject to word splitting.

#+begin_src 
expoort IFS=';'
for word in "a;b;c"; do
  eco $word
done
#+end_src

** Filename Expansion

=*=, =?= and =[= as glob pattern.

* Aliases

For interactive Use only.

- Aliases are not recursively expanded in replacement text.
  One may alias =ls= to =ls -F=

- Aliases are not in a non-interactive shell unless explicitly set.

- Aliases are not expanded until the line is read. 
  + Thus, an alias within a compound command is not available for subsequent commands.
  + Aliases used in a function are expanded when the function is read.
  + Aliases defined in a function are only enabled after that function is executed.

- Aliases are not inherited by child processes.

- While aliases are easier to understand, shells functions are preferred over aliases for almost every purpose.

* Developing Good Scripts

** Debugging

*** Verbose Output and Traces

- Traces of each command plus its arguments are printed to stdout after the
  commands have been expanded but before execution.
  + =set -x= or =set -o xtrace= and disabled with =set +x= or =set +o xtrace= 
   to trace only part of a script. 
  + =bash -x= enables tracing of the entire script.

- =-v= verbose output: prints shell input lines as they are read.

=-v= prints the raw input while =-x= shows the actual command executed.

*** Source-Level Debugger

bash supports extended debugging mode by loading the debugger profile.

- [[https://github.com/rocky/bashdb][bashdb]] :: a full-fledged debugger

* Job Control

Enabled by the =monitor= option. Job control is a shell feature to allow
multiple processes to run in a single shell: foreground/background (=fg=, =bg=,
=&=), suspend (=suspend=, =^Z=), status (=jobs=, =ps=). =$$= displays the current
shell PID, =$!= shows the the PID of the last command moved to the background.

Each command (job) entered is identifiied by a /job number/, (/job ID/). A job
refers to all the processes that are necessary to interpret an entire command
line. Jobs are controlled by the shell.

A foreground job may be suspended by =^Z=, then resumed by =fg=. When the user
logs out, all suspended jobs are terminated automatically. The current shell may
be suspended with =suspend= if it is not a login shell. =bg= is useful when the
command is not started with a =&= but later needs moving to the background (by
first suspending it).
