#+title: Posix Shell
#+bibliography: posix_shell_ref.bib


#+begin_quote
Writing shell scripts requires more than just a knownledge of the shell
language. It also requires familiarity with the individual Unix programs.
[cite:@robbins2005classic]
#+end_quote

* History

- Thompson Shell (Ken Thompson, Unix Version 1 throughout 6), modeled after the Multics shell =RUNCOM=,
  hence the =rc= configuration.

- Bourne Shell (Stephen Bourne, Unix Version 7). There are some modern alternatives:
  + Almquist Shell (ash), a clone of the original Bourne shell (FreeBSD, NetBSD, Busybox, dash)
  + Bourne-Again Shell: the GNU shell as a superset, the default interactive
    shell on most Linux distros.
  + KornShell (ksh), the POSIX shell is a subset of Korn shell, an enhanced
    version the Bourne shell.
    - ksh93 is the one commonly used.
  + Public domain Korn shell (pdksh): a clone of KornShell
    - the original pdksh development has ceased.
    - MirBSD Korn shell (mksh), used by Android as =/system/bin/sh=.
  + Z shell: a relatively modern shell compatible with bash.

- C shell (not POSIX-compliant): modelled after the C programming language. The TENEX C shell as an
  improved version is a modern alternative.

* Dash

This note uses =dash= as the POSIX shell due to its availability on Debian-based
Linux distros and its fully POSIX compliance. On Debian, Ubuntu and termux, =dash= is not configured with
=libedit= and thus gives no support for vi-mode line editing and history.

* Login & Non-Login Shell

A login shell (=-l=) first reads commands from the files =/etc/profile= and =.profile=.
It also reads =$ENV= if defined. In any case, there is no =.bashrc= or related startup scripts
for a POSIX shell. One has to rely on =$ENV= to set up for interactive shells.

* =expr= Expression Evaluator

=expr= (for Bash, it's part of coreutils as a separate command)
performs /arithmetic/, /logical/, /relational/ or /string/ operations.

- The traditional way to perform arithmetic before arithmetic expansion is introduced.
  Useful if arithmetic expansion is not available or suitable.
  Non-integer arithmetic is still not supported.

- Each token must be a separate argument.

- Equality test is done by ~=~ not ~==~

- Some operators (=*=, =&=, =|=, =<=, =>=, =(=, =)=) are special metacharacters
  and they must be quoted or escaped.

- If only one expression is given, then =expr= simply echos it.

- to avoid some variables that are themselves an operator string, append an =x= to them
  and another operand before string comparison.

- String matching =:= or =match= via *REGEXP* (BRE) is supported!
  + The pattern has an implicit =^= at the start, i.e. it matches at the beginning of the word.
  + the POSIX standard way to perform eregex matching directly in a pipeline.

- Note that =expr= prints the result while set the exit status at the same time.
  Be careful when using =expr= in a conditional construct.

* Variables

- No space before and after ===

- =set= prints all current variables

- Environment variables are exported variables, which propagate to subprocesses.
  Environment variables in inherited by child processes and they cannot be
  propagated back to the parent.
  + =env= prints all current environment variables

- to append strings to a variable, use =${x}appended=, =$x"appended"=.

- ~var=~ assigns null/empty to =var=; =unset var= undefines it.

** Common Environment Variables

- =PATH= :: the command search path

- =HOME= :: the user home

- =CDPATH= :: a list of directories for =cd= to find the destination directory in, in addition to
  =PWD=.

- =PS1=, =PS2= :: normal propmt before each command and the secondary prompt in
  a multiline command.

- =IFS= :: the characters used to tokenize the input.

** Parameter Substitution

- =${var?error_message}= :: complain with =error_message= if undefined

- =${var-default_option}= :: use =default_option= if undefined
  + =default_option= may be a variable, a quoted string, a command substitution
    etc. Any command inside =default_option= is lazily executed.

- =${var+option_on_defined}= :: use the new value if defined
  + this form may be used to add a debug message.

- ~${var=new_definition_if_undefined}~ :: use and define new value if undefined

The special expression in the back is executed in the current shell rather than
a subshell.

 Most scripts don't care about the difference between undefined variable and a
null variable. =:?=, =:-=, =:+=, =:== variations of the above forms check
whether the variable is null or undefined instead of simply undefined.

* Filename Expansion

Wildcards (=*=, =?=, =[=, =]=) in POSIX shells expands only filenames, not
random strings. They are not simplified regexp. They are expanded automatically when
they occurs in a shell. However, these filenames are still strings, passed to shell commands:
If a file =-i= exists and =rm *= is executed, it will turn =rm= into interactive =rm=.

- Files whose name starts with a dot are not normally listed and various
  shells, utilities follow this convention.
  + =.*= is required to list all files, otherwise only visible files are listed.

* Quoting

*Quoting in Shell does not mark string literals as in C*!

Metacharacters (including space) are commonly used in shell.
Quoted characters do not have a special meaning.
Metacharacters must be quoted or escaped to be treated as regular characters. 

POSIX shells supports multiline strings with ='= and ="= because =\n= 
retains its literal value.

#+begin_src shell
# these are equivalent
rm 'file1 file2'
rm file1' 'file2
rm f'ile1 file'2

# However these are the same: 
# the substitutions in a variable assignment aren't subject to further expansion
a=$b
a="$b"
#+end_src

Double quotes are weak in that certain meta-characters retain their special meaning:
- =$=: parameter expansion, command substitution, arithmetic expansion
- =``=: command substitution
- =\=: as the escape sequence prefix with =$=, =`=, ="=, =\=, newline
  + However, in ="$()"= and ="${...}"= the double quotes have no effect on special characters handling.

The easiest way to quote a quotation mark is to use another type of quotation marks.

- /Dollar single quotes/ =$'...'= allows ANSI C-style escape sequences to be interpreted within a quoted string.
  It is still strong quoting except that it escapes C-style sequences.
  #+begin_src shell
echo $'abc\nefg'  # we don't need -e anymore
  #+end_src
  + =\u= unicode escape sequence is required to be supported (supported by Bash, zsh, mksh, not by dash).
    For better portability, use =print= or =echo=

* Bibliography

#+print_bibliography:
