/* posix_profile.c generated by valac 0.48.6, the Vala compiler
 * generated from posix_profile.vala, do not modify */

#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

typedef struct _CompactClass CompactClass;
#define _compactclass_free0(var) ((var == NULL) ? NULL : (var = (compactclass_free (var), NULL)))

struct _CompactClass {
	gint a;
};

void compactclass_free (CompactClass * self);
G_DEFINE_AUTOPTR_CLEANUP_FUNC (CompactClass, compactclass_free)
static void compactclass_instance_init (CompactClass * self);
CompactClass* compactclass_new (gint arg);
gint _vala_main (gchar** args,
                 gint args_length1);

CompactClass*
compactclass_new (gint arg)
{
	CompactClass* self;
	self = g_slice_new0 (CompactClass);
	compactclass_instance_init (self);
	self->a = arg;
	return self;
}

static void
compactclass_instance_init (CompactClass * self)
{
}

void
compactclass_free (CompactClass * self)
{
	g_slice_free (CompactClass, self);
}

gint
_vala_main (gchar** args,
            gint args_length1)
{
	CompactClass* cc = NULL;
	CompactClass* _tmp0_;
	FILE* _tmp1_;
	gint result = 0;
	_tmp0_ = compactclass_new (5);
	cc = _tmp0_;
	_tmp1_ = stdout;
	fprintf (_tmp1_, "%d\n", cc->a);
	result = 0;
	_compactclass_free0 (cc);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

