#+title: Latex Basic

* TeX Ecosystem
:PROPERTIES:
:ID:       8656b469-9d27-4966-88dd-9fdc8f2ed662
:END:

TeX provides about 300 low-level /primitives/, augmented by Plain TeX's with 600
commands. Other macros packages (LaTeX, AMS-TEX) build their macros upon these
primitives and commands.

** Implementations

- the official implementation by Knuth is programmed in WEB, a mixture of TeX
  and a Pascal subset, converted to C with =web2c= sometimes.

** Extensions

*** LaTeX

a macro package written in TeX that provides high-level descriptive markup
language. TeX in LaTeX mainly handles the layout while LaTeX handles the
content. /Presentation/ is seperated from /content/.


* LaTeX Outline
:PROPERTIES:
:ID:       23aecf54-2fa4-4de5-b380-3bfdc13e0ce3
:END:

Typesetting comamnds start with =\= and arguments are placed inside ={}=. =\\=
starts a newline.

#+begin_src tex
\documentclass{}

\begin{document}
\end{document}
#+end_src

** LaTeX Sectioning
:PROPERTIES:
:ID:       24374627-53f2-4630-879f-1722cfa299b2
:END:

#+begin_src tex
\section{}
\subsection{}
#+end_src

* LaTeX Lists

- =\begin{itemize}...\end{itemize}= :: unordered list

- =\begin{enumerate}...\end{enumerate}= :: ordered list

* LaTeX Math
:PROPERTIES:
:ID:       c888c29d-4453-413f-aa80-4ed92dba139e
:END:

- =$= for inline math and =$$= for display math (centered on a dedicated line).

- Use =\begin{equation}= along with =\label= to make an equation referable.
