#+title: Coreutils

* =ls=

- =-1= :: one line per file

- =-t= :: sort by time in descending order, by default modification time (mtime).

- =-u= :: use access time (atime), =-c= use create time (ctime)

- =-S= :: file size

- =-r= :: reverse the order

* =pr=

A paginator that make text into forms suitable for paper pages, possibly in
multiple columns. By default 66 lines per page. Not a replacement for =troff= or
=nroff=. For real printing, consider =lp= and =lpr=.

* =date=

#+begin_src shell
date +%FT%T.%6N # millisecond
#+end_src

* =wc=

count lines, words, characters or bytes of a file.

* =sort=

- *Comparison*: By key (=-k=) or entire line.
- *Stability*: Unstable by default; =-s= preserves original order of equals.
- *Output*: Write to file via =-o=.
- *Operations*:
  - Default: Sort input.
  - =-c=, =-C=: Verify sortedness.
  - =-m=: Merge pre-sorted inputs.

** Key Definition

A key specifies a sorting segment using =-k POS1[,POS2]=.

- *Endpoint Format*: =FieldNumber.CharacterNumber.OrderingOption=
- *Defaults*:
  - Omitted end position: End of line.
  - Omitted character number: End of field.
- *Indexing*: 1-based.
- *Separator* (= -t=): Field delimiter. Default is a space or a tab.
- *Multiple Keys*: Applied in command-line order.

** Order

- Default: Ascending order
- =-r=: Makes it descending
- =-s=: Enables stable sort by retaining the original order of equal lines
** Comparison Rules

+ By default Keys are compared using the =LC_COLLATE= collating sequence.
+ Per-key options (including =-r=) override global settings.
+ Modifiers (except =-b=) apply to the full field, regardless of specifier position.
+ Any equal results are sorted by comparing the entire key, unless stable sort is enabled.

- leading blanks may be ignored =-b=

- =-f= ignores (folds) case

- =-i= ignores nonprinting characters

- /dictionary sort/ (=-d=): only letters are considered

- /numeric sort/ =-n=: sort by numeric keys (the line is assumed to start with a
  number field). Empty digit strings are considered zero (and then trailing
  non-digit characters are sorted as a last resort upon equal results). Affected by =LC_NUMERIC=.

  #+begin_quote
1. Lines that begin numerically are sorted by numeric value (smaller numbers come first)
2. Trailing characters on numeric lines do not affect the numeric portion,
   but the trailing characters are sorted alphanumerically if the numeric portion is the same.
3. Lines that begin non-numerically are sorted as if they were zero, and then by rule 2.
  #+end_quote

- /general numric sort/ =-g=: the number is taken as a double-precision
  floating-point number.

- /human numeric sort/ =-h=: understands SI suffixes.

- /version sort/, or /natural sort/: =-V= sort first by character and then by numeric, based Debian's
  package version sort. There is
  no standardized rules across various programming contexts.
  + strings are split into text, digits, text, digits ..., and then compared
    respectively. Empty numeric parts are seen as zero. ASCII letters precede
    other bytes in text substrings; =~= precedes all including empty strings.
  + text characters are compared byte by text, ignoring locales.

- /Month sort/ =-M=: sort by month name abbreiviation, affected by =LC_TIME=

- /Random sort/ =-R=: a random permutation of the input by hashing the input
  keys and then sorting the hash values. Lines with equal hash values are sorted together.

** Input

From command line or files. Zero-terminated filenames are supported with =--files0-from=FILE=.

** Output

- unique output: =-u= output only the first of a sequence of equal lines (in the original order)

- zero-terminated instead of newline-terminated: =-z=

- compressed output with an external compression program: =--compress-program=PROG=

** Performance

- =-S SIZE= controls sort buffer size.

- =--parallel=N= threaded sort

** Examples

#+begin_src shell
# Decorate-Sort-Undecorate: add a length field, sort by length, remove the length field
awk '{print length, $0}' /etc/passwd | sort -n | cut -f2- -d' '

sort -u file1 file2 # union of unsorted files
#+end_src

* =file= (Non-coreutils)

- =-i=: output mime type

- =-0=: output =\0= after the end of the filename

* =od=

Not limited to octal format

- =-j= skip bytes and =-N= read N bytes

- =-t=: format (hexadecimal), unsigned decimal, signed decimal, floating point, .
  octal, named character, printable character or backslash escape
  + a size number after the format specifier indicates the number of bytes per group.
  + =z= prefix to print data as printable characters
  + =-A=: the address format, that is, the first number of each line that indicates
    the current address of the line beginning.

- =-w=: N bytes per line 

* =cut=: Selects Part of Lines

confer. =Select= in PowerShell. 

Selects by bytes, characters (currently still as byte characters, not Unicode code points),
or fields, 

Byte-based, does not understand Unicode. Also, cut outputs fields in the original read order. 
=awk= or =sed= is required by POSIX and available on nearly every Linux distro (cannot be removed on Debian)
unless it's a stripped-down system with only a stripped-down =busybox= (even =busybox= has =awk= but it may not be configured.).

#+begin_src 
asserter_20260307_231427328.log
asserter_20260307_231635953.log
asserter_20260307_231650640.log
asserter_20260307_231711250.log
asserter_20260307_231720125.log
asserter_20260307_231818468.log
asserter_20260307_231832015.log
asserter_20260307_231905781.log
asserter_20260307_231923687.log
asserter_20260307_233052109.log
asserter_20260307_233602578.log
asserter_20260307_233919562.log
#+end_src

- format: item list (=a,b,c,d=), or ranges (=N1-N2[,more ranges],=)
  + list of items, or list of ranges.
  + missing one end of a range means =1= or end of line
  + overlapping ranges or repeated elements only result in a single write.
    in the original order.
    #+begin_src shell
   ls *.log -1 | cut -f 3,2,1,1,1 -d '_'
asserter_20260307_231427328.log
asserter_20260307_231635953.log
asserter_20260307_231650640.log
asserter_20260307_231711250.log
asserter_20260307_231720125.log
asserter_20260307_231818468.log
asserter_20260307_231832015.log
asserter_20260307_231905781.log
asserter_20260307_231923687.log
asserter_20260307_233052109.log
asserter_20260307_233602578.log
asserter_20260307_233919562.log
    #+end_src

- the number of bytes, characters or fields starts at *1*.

* =paste=

concatenate one line from a file and one file from another file.

* =join=

We have =cut= to select, we might as well have =join= to join lines by a field as the key.
This command is supposed to process a table (e.g. csv, possibly with a header line.

- =join= does not force the input files be in a sorted order but requires so.

- the exact field as the join key can be specified as options..

- the output field can be specified by =-o=, =-o FileN.FieldM[,FileN,FieldM]=

- =-t= field delimiter.

- for outer join, consider =-a= (specify left join, right join or full join) and =-e= (default value for missing fields)

#+begin_src shell
# -t '' takes the entire line as the key
join -t '' -a1 -a2 file1 file2     # Union of sorted files
join -t '' file1 file2             # Intersection of sorted files
join -t '' -v2 file1 file2         # Difference of sorted files
join -t '' -v1 -v2 file1 file2     # Symmetric Difference of sorted files
#+end_src

* =uniq=

Like =join=, the input should be presorted: only repeated adjacent lines are processed.

- Set intersection or difference =-d= (repeated lines only)
  + =sort file1 file2 | uniq -d= intersection unsorted files
  + =sort file1 file1 file2 | uniq -u= difference of unsorted files, all lines in =file1= are repeated, any line in =file2= what is also 
    in =file1= is also repeated.

- Symmetric difference =-u= (unique lines only, repeated lines are not printed.)

* =tail=

- =-n +N= skip =N-1= lines.
