#+title: Coreutils

* =ls=

- =-1= :: one line per file

- =-t= :: sort by time in descending order, by default modification time (mtime).

- =-u= :: use access time (atime), =-c= use create time (ctime)

- =-S= :: file size

- =-r= :: reverse the order

* =pr=

A paginator that make text into forms suitable for paper pages, possibly in
multiple columns. By default 66 lines per page. Not a replacement for =troff= or
=nroff=. For real printing, consider =lp= and =lpr=.

* =wc=

count lines, words, characters or bytes of a file.

* =sort=

- *Comparison*: By key (=-k=) or entire line.
- *Stability*: Unstable by default; =-s= preserves original order of equals.
- *Output*: Write to file via =-o=.
- *Operations*:
  - Default: Sort input.
  - =-c=, =-C=: Verify sortedness.
  - =-m=: Merge pre-sorted inputs.

** Key Definition

A key specifies a sorting segment using =-k POS1[,POS2]=.

- *Endpoint Format*: =FieldNumber.CharacterNumber.OrderingOption=
- *Defaults*:
  - Omitted end position: End of line.
  - Omitted character number: End of field.
- *Indexing*: 1-based.
- *Separator* (= -t=): Field delimiter. Default is a space or a tab.
- *Multiple Keys*: Applied in command-line order.

** Order

- Default: Ascending order
- =-r=: Makes it descending
- =-s=: Enables stable sort by retaining the original order of equal lines
** Comparison Rules

+ By default Keys are compared using the =LC_COLLATE= collating sequence.
+ Per-key options (including =-r=) override global settings.
+ Modifiers (except =-b=) apply to the full field, regardless of specifier position.
+ Any equal results are sorted by comparing the entire key, unless stable sort is enabled.

- leading blanks may be ignored =-b=

- =-f= ignores (folds) case

- =-i= ignores nonprinting characters

- /dictionary sort/ (=-d=): only letters are considered

- /numeric sort/ =-n=: sort by numeric keys (the line is assumed to start with a
  number field). Empty digit strings are considered zero (and then trailing
  non-digit characters are sorted as a last resort upon equal results). Affected by =LC_NUMERIC=.

  #+begin_quote
1. Lines that begin numerically are sorted by numeric value (smaller numbers come first)
2. Trailing characters on numeric lines do not affect the numeric portion,
   but the trailing characters are sorted alphanumerically if the numeric portion is the same.
3. Lines that begin non-numerically are sorted as if they were zero, and then by rule 2.
  #+end_quote

- /general numric sort/ =-g=: the number is taken as a double-precision
  floating-point number.

- /human numeric sort/ =-h=: understands SI suffixes.

- /version sort/, or /natural sort/: =-V= sort first by character and then by numeric, based Debian's
  package version sort. There is
  no standardized rules across various programming contexts.
  + strings are split into text, digits, text, digits ..., and then compared
    respectively. Empty numeric parts are seen as zero. ASCII letters precede
    other bytes in text substrings; =~= precedes all including empty strings.
  + text characters are compared byte by text, ignoring locales.

- /Month sort/ =-M=: sort by month name abbreiviation, affected by =LC_TIME=

- /Random sort/ =-R=: a random permutation of the input by hashing the input
  keys and then sorting the hash values. Lines with equal hash values are sorted together.

** Input

From command line or files. Zero-terminated filenames are supported with =--files0-from=FILE=.

** Output

- unique output: =-u= output only the first of a sequence of equal lines (in the original order)

- zero-terminated instead of newline-terminated: =-z=

- compressed output with an external compression program: =--compress-program=PROG=

** Performance

- =-S SIZE= controls sort buffer size.

- =--parallel=N= threaded sort

** Examples

#+begin_src shell
# Decorate-Sort-Undecorate: add a length field, sort by length, remove the length field
awk '{print length, $0}' /etc/passwd | sort -n | cut -f2- -d' '
#+end_src

* =file= (Non-coreutils)

- =-i=: output mime type

- =-0=: output =\0= after the end of the filename

* =od=

Not limited to octal format

- =-j= skip bytes and =-N= read N bytes

- =-t=: format (hexadecimal), unsigned decimal, signed decimal, floating point, .
  octal, named character, printable character or backslash escape
  + a size number after the format specifier indicates the number of bytes per group.
  + =z= prefix to print data as printable characters
  + =-A=: the address format, that is, the first number of each line that indicates
    the current address of the line beginning.

- =-w=: N bytes per line 
