#+title: Coreutils

* =ls=

- =-1= :: one line per file

- =-t= :: sort by time in descending order, by default modification time (mtime).

- =-u= :: use access time (atime), =-c= use create time (ctime)

- =-r= :: reverse the order

* =pr=

A paginator that make text into forms suitable for paper pages, possibly in
multiple columns. By default 66 lines per page. Not a replacement for =troff= or
=nroff=. For real printing, consider =lp= and =lpr=.

* =wc=

count lines, words, characters or bytes of a file.

* =sort=

Lines are compared by specified by fields/keys (=-k=), or the entire line if
none. Equal lines are ordered according to the entire line unless stable sort =-s=
(=--stable=) is specified, which retains the original order. Output may be saved
to a file =-o=.

=sort= by defaults sorts concatenated files, otherwise checks if the files are
sorted (=-c=, =-C=), or merges already-sorted files without sorting them (=-m=).

** Key Definition

A key is a field (or part of a field) or the part of a line between two keys
(inclusive). The key is specified in the format of
=EndpointFieldNumber.EndpointCharacterNumber.OrderingOption=. The count starts at 1 not
0, which denotes the last one.

Separators are specified by =-t=, by default unintuitively the empty string between a
non-blank character and a blank character, not blank characters.

** Order

By default in ascending order, =-r= makes it descending. =-s= enables stable
sort by retaining the original order of equal lines.

** Comparison Rules

By default, keys
are compared using the collating sequence of =LC_COLLATE=. All these sort
options including =-r= may be used as options within the key definition to
override the global ordering for that key.

- leading blanks may be ignored =-b=

- =-f= ignores case

- =-i= ignores nonprinting characters

- /dictionary sort/ (=-d=): only letters are considered

- /numeric sort/ =-n=: sort by numeric keys (the line is assumed to start with a
  number), affected by =LC_NUMERIC=

- /general numric sort/ =-g=: the number is taken as a double-precision
  floating-point number.

- /human numeric sort/ =-h=: understands SI suffixes.

- /version sort/, or /natural sort/: =-V= sort first by character and then by numeric, based Debian's
  package version sort. There is
  no standardized rules across various programming contexts.
  + strings are split into text, digits, text, digits ..., and then compared
    respectively. Empty numeric parts are seen as zero. ASCII letters precede
    other bytes in text substrings; =~= precedes all including empty strings.
  + text characters are compared byte by text, ignoring locales.

- /Month sort/ =-M=: sort by month name abbreiviation, affected by =LC_TIME=

- /Random sort/ =-R=: a random permutation of the input by hashing the input
  keys and then sorting the hash values. Lines with equal hash values are sorted together.

** Output

- unique output: =-u= output only the first of a sequence of equal lines (in the original order)

- zero-terminated instead of newline-terminated: =-z=

- compressed output with an external compression program: =--compress-program=PROG=

** Performance

- =-S SIZE= controls sort buffer size.

- =--parallel=N= threaded sort
