#+title: System Monitor

* Ps

The so-called BSD style options has never really existed in BSDs and it is
entirely a Linux invention. Use the POSIX/UNIX personality for portabilility.

#+begin_src shell
ps -e # all processes
ps -ef # all processes full format
ps -o pid,comm,args,pcpu,pmem # comm for command name and args for full command line
#+end_src

* pstree

Display a tree of processes.

Child processes of the same name are merged as =n*[procname]=; child threads are
shown in curly braces =[{threads}]=.

=ps -H= also shows processes as a tree.

* fuser

Lists all the processes that are using a specific file or socket.

* Top

Top has ha proper readable manual.

- =h=, =?=, =q=

- =-e=, =-E=: change memory unit.

- =-o=: sort by a certain field

- =-p=: monitor PIDs.

** Interactive

- =<Enter>=, or =<Space>=: refresh display

- =?=, =h=: help

- =d=, =s=: change delay time interval

- =H=: threads-mode toggle

- =E=: memory scaling in summary area; =e=: memory scaling in task area.

- =k=: kill a task

- =J=, =j=: justify

- =x=: toggle column highlighting

- =<=, =>=: move the current sort column

- =R=: reverse sort order

- =F=: configure fields

- =L=: locate a string; =&=: locate next

- =O=: filter =COLUMN=<>VALUE=; ===, =+=: reset filters
