#+title: Intel Early History

This note covers the history of Intel CPU before modern Core microarchitectures
since 8086.


* Before x86

- *4004*: as the first significant example of LSI with MOS gates, mainly used for calculators
  + 4-bit bus
  + highly integrated, requires fewer external components, mostly as embedded controllers.

- *8008* (1972): more flexible but requires more external circuits.
  + 8-bit data bus, 14-bit address bus (16K memory)
  + partially implemented interrupt mechanism
  + the CPU for the very first commercial non-calculator PCs.

- *8080* (1974): 8008 with registers expanded. A CPU-on-a-chip that is not a
  full product.
  + 8-bit data path, 16-bit address bus
  + extended and enhanced variant of 8080 without binary compatibility but with
    the same basic instruction set and register model. Many of the instructions
    survived into x86.
  + a 8224 clock generator and a 8228 bus controller are required for 8080 to function.
  + a new dedicated stack pointer instead of the internal 7-level call stack.
  + 256 I/O ports in a dedicated I/O address space.

- *8085* (1976): a enhanced version of 8080 implemented with depletion-mode transistors
  + binary compatible with 8080 with only two instructions added
  + 8-bit data width, 16-bit address width

** Similar Processors From Other Vendors

- *Zilog Z80*:
  + designed by none other than Fedrico Faggin, one of the designer of Intel 8080.
  + backward-compatible with Intel 8080 with increased performance and features.
  + wide spread in video game systems and home computers in the '70s and the
    early '80s.

* 8086 (launched in 1978)

A non-strict extension of 8080,basically the same microarchitecture as 8085.

A mixture of random logic and microcode.

- clock frequency 5MHz - 10Hmz

- 40-pin DIP package.

- 16 bit data width: all internal registers as well as internal and external
  data buses are 16-bit wide.
  + multiplexed with the address bus.

- 20 bit address width

- pipelined instruction prefetch

8086 is divided into an Execution Unit (EU) and a Bus interface Unit (BIU). The
BIU is responsible for handling all interfaces with external bus. When the EU
needs to access memory, it make a request to the BIU. When there is no requests
from the EU, the BIU fetches machine instructions from the memory into the
instruction queue.

An additional 8284 clock generator and a 8288 bus controller are required.

8086 is designed to work in a multiprocessing system.

** 8088

A binary-compatible cheap version of 8086, with the external data width reduced
8-bit, thus more compatible with then 8-bit compouter design for IBM.

* 80286 (1982)

- designed for multi-user systems with multitasking applications including
  communications and real-time process control.

- the data bus and the address bus are not multiplexed anymore

- More than 100% performance increase compared to 8086/8088, mainly due to fast
  address calculations and separate address and data buses

- 1.5 micrometer process

- 4MHz to 25MHz

- 24-bit address width, up to 16 MB memory

- On-chip MMU with virtual memory support up to 1GB via segmentation (4 pairs of
  segment registers combined).

** Protected Mode


*** Limitation

- /No easy switch between protected mode and real mode/: reverting from protected mode to real mode requires a hardware-initiated reset (not necessarily a reboot and memory clearance). This caused heavy performance penalty and protected mode is not widely used until 80386. Real mode was designed only for bootstrapping. The OS should run in protected mode.

- /limited address capacbility with 16-bit registers/: an offset register is only 16-bit and four combined provide only 256 KB memory for direct access. Reloading a segment register in protected mode caused a 6-byte segment descriptor to be loaded into the CPU from memory (performance penalty!).

*** Compatibility with Real-Mode DOS Programs

In protected mode, memory management and interrupt handling were done
differently than in real mode and memory that does not belong to one program is
not accessible (intended by design), which is incompatible with existing DOS programs.

** OS Support

- Concurrent DOS 286: run fully in protected mode with real mode program compatibilty

- Microsoft Xenix

- Minix

* 80386

Fully 32-bit CPU (internal registers, buses and external buses).

- Up to 4GB physical memory and 64 TB virtual memory

** 386SX

A reduced version with 16-bit external data bus and a 24-bit address bus.

* 80486
