* Dynamic or Static

There is no dynamic scoping in Python. Although it seems so
when resolving a name from local up to enclosing, module and global.
A nested function is using a variable from its caller but this is 
not strictly determined dynamically
and it can be actually determined statically.

In dynamic scoping, the value of a variable is determined by the closest
calling namespace where a value is set. A nested function in Python might 
use a variable of its enclosing function but it does always so while in 
dynamic scoping, even a non-nested function may use a variable that is 
defined by its caller, which may only occur in Python with a nested function.

* Variable Scopes

*Only classes, functions and modules provide scope in Python*. =if= does not count.
This differs greatly from C, where ={}= blocks and =if= statements create scopes.

Python variables are scoped to the innermost function, class, or module in which they're assigned. 
Control blocks like if and while blocks don't count, 
so a variable assigned inside an if is still scoped to a function, class, or module.
