#+title: Mingw

* Windows XP Support

- a modified MSYS2 is available [[https://archive.org/details/msys2xp][here]], with many userland utils replaced by =busybox=. Another way to get proper Bash support
  is =Git= v2.10.0 (relased on 2016-08-25).

- [[https://sourceforge.net/projects/mingwbundle/][mingwbundle]]: a bundled MSYS with legacy MinGW toolchains.

- [[https://github.com/niXman/mingw-builds-binaries/releases][Mingw Builds]]: the official MinGW-w64 builds work before v12 (2022). Its bundled gdb
  does not. Some versions of [[https://github.com/ssbssa/gdb][this]] unofficial Windows build of gdb may
  complement.

- [[https://github.com/brechtsanders/winlibs_mingw][Winlibs]]: working builds include =mingw32-make= (the most common one used by various
  build tools on Windows)
  + GCC 7.5.0 + MinGW-w64 7.0.0 (release 1), =gdb= works
  + GCC 8.4.0 + MinGW-w64 7.0.0 (release 1), =gdb= fails
  + GCC 9.2.0 + MinGW-w64 7.0.0 (release 4), =gdb= fails

- [[https://github.com/skeeto/w64devkit][w64devkit]]: very nice build that includes Windows XP support and the latest GCC
  and a simple Unix environment.

** Powershell

v2, lacking too many functionalities, not of much use.

** Notepad++

The last working version is v7.9.2

** CMake

The last working version is v3.13.5.

** Ninja

The last official build runnable on XP is v1.6.0 (2015-01-30)

** LLVM

the last supported version is 3.7.1, which is only better than GCC 4.

** MSVC

Visual Studio 2010; Windows SDK 7.1 (MSVC 16.00)

** Python

The last officially supported version of Python is 3.4.4 (EOL March 2019), and pip version 19.1.1.
Use =python -m pip= to upgrade pip before any online =pip install= could succeed.
Various packages may be installed using pip as of 2024, sometimes by compiling
from source
and most are relatively new. If not, use =pip download --platform win32= to
download on other systems.

- =ipython=: 4.2.1

- =numpy=: 1.16.6

- =scipy=: 1.2.3

- =scikit-learn=: 0.15.2

- =theano=: 1.0.5

- =keras=: 2.10.0

- =pillow=: 5.4.1

- =matplotlib=: 2.2.5

- =pandas= 0.22.0

- =pyodbc=: 4.0.32

- =cx_oracle= 6.4.1

- =pymysql= 0.9.3

- =psycopg2=: 2.8.6

- =cython=: 3.0.11

- =pywin32=: 221, use =easy_install pywin32.exe= to install it into a virtual environment.

- =pygame=: 2.0.1

** Java

Only JDK 8 is supported, with a build from [[https://github.com/ojdkbuild/ojdkbuild/releases][ojdkbuild]].

** Go

Golang 1.10

** FreePascal

Still works as of 3.2.2 and Lazarus 3.4

** FreeBASIC

Still works as of 1.10.1

** Nim

Seems to work as of 2.0.8

** .NET

The latest .NET Framework version supported on Windows XP is v4.0.
However, Mono 3.2.3 provides .NET 4.5 support with a C# 5 compiler, and
possibly supports Roslyn 1.3.2 but Roslyn has a bug that considers the second
positional argument the source file (under mono, =csc.exe= is the second
argument),
fixed only since Roslyn 2.0, which unforunately requires .NET 4.6.

* [[https://www.mingw-w64.org/][MinGW-w64]]

The current de-factor standard GCC on Windows.

- Support from Windows 2000

- Has DDK and DirectX support from other projects.

- provides optional secured C-runtime API and headers

** Binary Distributions

- [[https://sourceforge.net/projects/mingw-w64/][Official SourceForge]]: binary releases are unmaintained.

- [[https://github.com/niXman/mingw-builds-binaries][Mingw-builds]]: After GCC v11.2

- [[https://winlibs.com/][WinLibs]]: actively maintained comprehensive toolchains that includes GCC, LLVM
  and various other tools.
  + has support for [[https://github.com/lhmouse/mcfgthread/][MCF threading library]]
  + with MSVCRT and UCRT as CRTs.

- [[https://github.com/skeeto/w64devkit][w64devkit]]: GCC, GDB, GNU Make, NASM, Vim, Ctags, busybox with Windows XP
  backwards compatibility

- [[https://www.msys2.org/][MSYS2]]: provides not only GCC toolchains, but a whole Unix-like environment.
  + rolling-release.

- [[https://gcc-mcf.lhmouse.com/][GCC-MCF]]: GCC with the MCF threading library (a reimplementation of the gthread
  interface set, requires Windows 7 or later)

- [[https://jmeubank.github.io/tdm-gcc/][TDM-GCC]]: provides both MinGW.org and MinGW-w64 versions with various patches.
   None work with Windows XP anymore.
   + uses =winpthreads= for POSIX threading support.

- the famous Cygwin provides native MinGW-w64 GCC.

- [[https://github.com/mstorsjo/llvm-mingw][llvm-mingw]]: not GCC.

** Components

*** [[https://sourceforge.net/p/mingw-w64/wiki2/gendef/][gendef]]

TODO

*** genidl

TODO

*** widl


** Cross Compilation

- Build triplets: =i686-w64-mingw32= and =x86_64-w64-mingw32=.

TODO

** Unicode

- =wmain=: UTF-16 environment and command line arguments, as well as a MBCS version.
  +  =-municode= is necessary and the macros =_UNICODE= (for =tchar.h=) and =_UNICODE= (for Win32 API functions) should be defined.
  + =wmain= should be marked as =extern "C"= under C++.

** C Standard Confornmance

*** =printf= family

- The [[https://mingw.osdn.io/][Old MinGW]] seems to accept =%s= with =wchar_t*=, the standard way
  is to use =%ls=, to which MinGW-w64 complies (with =%s= and =wchar_t*=
  the output is completely blank).

- MinGW by default uses the builtin old =MSVCRT.DLL=, which does not have a C99
  implementation of =printf=.

- MinGW-w64 provides its own =__mingw_printf= (enabled with
  =__USE_MINGW_ANSI_STDIO=1=) as a conformant replacement for =printf=.
  + as MinGW-w64 v8.0.0, =USE_MINGW_ANSI_STDIO= is enabled automatically with MSVCRT.

** [[https://reactos.org/wiki/PSEH][PSEH]]: SEH Handling

#+begin_src cpp
#include <pseh/pseh.h>

#include <windows.h>
#include <iostream>


using std::cout;

extern "C"
int wmain(int argc, wchar_t *argv[]) {
    _SEH_TRY {
        int a = 4;
        int b = a / 0;
    }
    _SEH_HANDLE {
        std::cout << "divied by zero: " << std::hex << _SEH_GetExceptionCode() << '\n';
    }
    _SEH_END;

    return 0;
}
#+end_src

*** =__try1=

Sorta works, but limited

[[https://sourceforge.net/p/mingw-w64/mailman/message/35219710/][Report on __try1 and SEH]]

[[http://www.programmingunlimited.net/siteexec/content.cgi?page=mingw-seh][SEH and MinGW]]
