#+title: Windows XP Support

* GCC

- a modified MSYS2 is available [[https://archive.org/details/msys2xp][here]], with many userland utils replaced by =busybox=. Another way to get proper Bash support
  is =Git= v2.10.0 (relased on 2016-08-25).

- [[https://sourceforge.net/projects/mingwbundle/][mingwbundle]]: a bundled MSYS with legacy MinGW toolchains.

- [[https://github.com/niXman/mingw-builds-binaries/releases][Mingw Builds]]: the official MinGW-w64 builds work before v12 (2022). Its bundled gdb
  does not. Some versions of [[https://github.com/ssbssa/gdb][this]] unofficial Windows build of gdb may
  complement.

- [[https://github.com/brechtsanders/winlibs_mingw][Winlibs]]: working builds include =mingw32-make= (the most common one used by various
  build tools on Windows)
  + GCC 7.5.0 + MinGW-w64 7.0.0 (release 1), =gdb= works
  + GCC 8.4.0 + MinGW-w64 7.0.0 (release 1), =gdb= fails
  + GCC 9.2.0 + MinGW-w64 7.0.0 (release 4), =gdb= fails

- [[https://github.com/skeeto/w64devkit][w64devkit]]: very nice build that includes Windows XP support and the latest GCC
  and a simple Unix environment.

* Powershell

v2, lacking too many functionalities, not of much use.

* Notepad++

The last working version is v7.9.2

* CMake

The last working version is v3.13.5.

* Ninja

The last official build runnable on XP is v1.6.0 (2015-01-30)

* LLVM

the last supported version is 3.7.1, which is only better than GCC 4.

* MSVC

Visual Studio 2010; Windows SDK 7.1 (MSVC 16.00)

* Python

The last officially supported version of Python is 3.4.4 (EOL March 2019), and pip version 19.1.1.
Use =python -m pip= to upgrade pip before any online =pip install= could succeed.
Various packages may be installed using pip as of 2024, sometimes by compiling
from source
and most are relatively new. If not, use =pip download --platform win32= to
download on other systems.

- =ipython=: 4.2.1

- =numpy=: 1.16.6

- =scipy=: 1.2.3

- =scikit-learn=: 0.20.4

- =theano=: 1.0.5

- =keras=: 2.10.0

- =pillow=: 5.4.1

- =matplotlib=: 2.2.5

- =pandas= 0.22.0

- =pyodbc=: 4.0.32

- =cx-Oracle= 6.4.1

- =pymysql= 0.9.3

- =psycopg2=: 2.8.6

- =cython=: 3.0.11

- =pywin32=: 221, use =easy_install pywin32.exe= to install it into a virtual environment.

- =pygame=: 2.0.1
  + requiring prebuilt binaries, for which downloading is prevent by TLSv1.3.
    Succeeded in manual building of the source package by editing the download URL.

- =wxPython=: 4.0.6 (4.0.7 is supposed to work but fails to build with MSVC 16)

- =sqlalchemy=: 1.3.24

** Python 2.7

The last (maybe) supported version is Python 2.7.9 with pip 20.3.4 (higher
versions are not tested) support. =venv= is not available but =virtualenv= is an alternative.

One nice thing about Python 2.7 on Windows XP is that its features are frozen
and thus any new package that still supports Python 2.7 is most likely runnable
on WinXP. It may support newer packages than Python 3.4.3 and it really does.

- =ipython=: 5.10.0

- =pymysql=: 0.10.1

- =cx-Oracle=: 7.3

- =pywin32=: 228 (not extensively tested, at least importable)

- =numpy=: 1.16.6

- =pillow=: 6.2.2

- =pandas=: 0.24.2

- =sqlalchemy=: 1.4.54

- =wxPython=: 4.0.7.post2

- =pygame=: 2.0.3

The disadvantage is the lack of =asyncio= and some other packages and language features.

* Java

Only JDK 8 is supported, with a build from [[https://github.com/ojdkbuild/ojdkbuild/releases][ojdkbuild]].

* Go

Golang 1.10

* FreePascal

Still works as of 3.2.2 and Lazarus 3.4

* FreeBASIC

Still works as of 1.10.1

* Nim

Seems to work as of 2.0.8

* .NET

The latest .NET Framework version supported on Windows XP is v4.0.
However, Mono 3.2.3 provides .NET 4.5 support with a C# 5 compiler, and
possibly supports Roslyn 1.3.2 but Roslyn has a bug that considers the second
positional argument the source file (under mono, =csc.exe= is the second
argument),
fixed only since Roslyn 2.0, which unforunately requires .NET 4.6.
