* CSC

There are two major C# compilers from Microsoft (the old CSC and Roslyn) and one from the Mono project (=mcs=):
all have similar CIL options. Regarding features, the old CSC supports only C# 5 and =mcs= has only partial support
for C# 7. As of 2026, Roslyn is the only recommended one.

** =csc.exe= and =csc.dll=

The old =csc.exe= is used with Mono/NETFX while =csc.dll= that comes along with the =dotnet= tool
can generate for the old .NET and the new one. =csc.exe= automatically references a great number of assemblies 
used by .NET Framework with =csc.rsp=. With =csc.dll= referenced libraries have to be passed explicitly 
or with a response file =.rsp=. For .NETFX target =mscorlib.dll= has to be passed 
(it is even included in .NETStandard nuget package).

There is no inherent difference between a CIL DLL file and a CIL EXE file generated by either compiler program: 
They simply have different names aside from some loaded-related stuff.
If a program references .NET Standard reference assemblies, 
both =mono= and =dotnet= can load it and execute it, provided that necessary config files 
are present (=.runtimeconfig.json= for =dotnet=). Referenced .NET libraries are resolved at runtime and an executable 
.NET program can target .NET Standard.

#+begin_src csharp
# reference all .NETStandard reference assemblies
dotnet csc.dll @csc.rsp  -lib path/to/netstandard2.1/ myprog.cs -out:myprog.exe
mono myprog.exe # totally runnable
dotnet myprog.exe # with a myprog.runtimeconfig.json, totally runnable
#+end_src
