#+title: Emacs


- *keymaps*: Emacs binds keys to named commands, a special type of Lisp function.

- =C-h= to invoke help

* Editing

** Insertion


- =C-j=: newline (useful in minibuffer)

- =C-q= to insert any non-graphic characters.

- =C-x 8 RET=: inserts unicode characters.

- =C-o=: insert a blank line after (=C-x C-o=) delete blank lines.

** Point (Cursor) Navigation

- =M-g M-g=: =goto-line=

- =M-g TAB=: move to column

- To navigate a line visually, set =line-move-visual= to =t=

** Cursor location

- =line-number-mode=, =column-number-mode=, =hl-line-mode= (highlight), =display-line-mode=

- =what-line=, =C-x ==

- =count-words=, =M-== (=count-words-regioin=)

** Numeric arguments

- =digit-argument=, =negative-argument=, =universal-argument=: specifies arguments for the next command (not necessarily a repetition). To force a repetition, use =C-x z= after the command.

  To use arguments with a named command, specify the argument before running =M-x= with the command.

** Minibuffer

The area under the modeline, used also by the echo area.

*** Minibuffer Completion

=TAB=, =SPC=, =RET=, =?=, use with =M-v= (switch to the completion list)

*** Minibuffer History

- =previous-history-element=, =next-history-element=, =list-command-history=

- =C-x ESC ESC=: reexecute a recent minibuffer command

* Help

- =C-h=

- =C-h a=: searches for commands

- =C-h b=: describe bindings

- =C-h d=: search in documentation for keywords

- =C-h i=: the GNU Info manual

- =C-h f=: describe functions

- =C-h C-f= the Emacs FAQ

- =C-h p=: lists available Emacs packages

* Region, Mark

- *Mark*: the initially starting end of the selected region.

- *Mark Ring*: each buffer remembers previous locations of the mark in the *mark ring*. Setting a mark and then releasing it saves the mark in the mark ring.
  + =C-u C-SPC=: move the cursor back to the previous mark.
  + A global mark ring exists alongside the buffers' ring. =C-x C-SPC= jumps to the buffer and position of the latest entry in the global ring (saved at the same time as in a buffer's ring).

- =C-SPC=, =C-@=: set the mark at point, enter the mark mode

- =C-x C-x= (=exchange-point-and-mark=): switch between the cursor and the mark

- =SHIFT=-selection together with certain cursor motion commands: =S-M-f=

- =M-@=: move mark to the end of the next word, =C-M-@=: mark to the end of following balanced expression.

- =C-x h=: =mark-whole-buffer=; =C-x C-p= (=mark-page=)

** Operating on the Region

- =C-w=: =kill-region=, =M-w=: =kill-ring-save=.

- =M-%=: =query-replace=, query whether to replace and replace if yes.

- =C-x TAB=: indent

* Killing And Moving Text

- *killing*: erasing text and saving it into the kill ring.

- *yanking*: pasting the text from the kill ring back into the buffer.

Killing also copies text to the system's clipboard.

** Deletion

- Delete blanks: =M-\= (delete whitespaces around point), =M-SPC= (delete all but =just-one-space=), =M-^=: move the current line up by deleting the previous newline, while =C-x C-o=: deletes the next newline of the current line.

** Killing

- =C-k=: =kill-line= (kill to the next line), works with arguments

- =C-S-backspace=: =kill-whole-line=, works with arguments.

- =C-w=: =kill-region=; =M-w=; =M-d=: =kill-word=; =M-BACKSPACE=: =backward-kill-word=;

- =C-M-k=: =kill-sexp=

- =M-z char=: =zap-to-char= (kill to the next occurrence of the character).

** Yanking

Emacs respects the system's clipboard.

- =C-y= (with arguments earlier kills are inserted), =M-y= (=yank-pop=, choose from the kill ring).

- =C-M-w= + kill command: kill the text and append/prepend it to the previous kill entry.

- =mouse-yank-primary=: yanks the primary selection under X. The secondary selection of X is rarely used.

- =append-to-buffer=, =prepend-to-buffer=, =copy-to-buffer= (destroy and copy), =insert-buffer=, =append-to-file=

** Rectangles

There are two ways to do rectangle operations.

- The Rectangle commands, starting with =C-x r=: =C-x r k=, =C-x r M-w=, etc.

- Enter the rectangle mark mode with =C-x SPC= and use normal commands.

* Register

- *Register*: positions, text, rectangles, numbers, windows configurations, a file name are saved for later use.

- *Bookmark*: records files and positions.

** Saving Positions

- =C-x r SPC a=: =point-to-register= record the position of point and the current buffer in register =a=

- =C-x r j a=: =jump-to-register= =a=

** Saving Text

- =C-x r s r=: =copy-to-register=; =append-to-register=, =prepend-to-register=

- =C-x r i r=: =insert-register=

* Controlling the Display

- =scroll-down-command=, =scroll-up-command=, =scroll-down=, =scroll-up= scrolls text, not the window, opposite to what modern editors do.

- =recenter=, =C-l= (=recenter-to-bottom=, with arguments, this scroll the page to put the point at a certain line in the window, =C-u C-l= recenters), =C-M-l= (=reposition=).

- =view-mode=: =SPC= and =S-SPC= to scroll

- =follow-mode=: scroll two buffers that shows the same buffer together

- =C-x <= (=scroll-left=), =C-x >= (=scroll-right=)

- Narrowing: =C-x n n= (=narrrow-to-region=), =C-x n w= (=widen=), =C-x n p= (=narrow-to-page=), =C-x n d= (=narrow-to-defun=). To get the current point after narrowing, use =C-x ==.

** Faces

*Faces*: different text styles. Each face can specify various /face attributes/: font, height, weight, slant, foreground and background color.
=list-faces-display= displays all faces.

TODO

* Searching and Replacement

- =C-s=, =C-r=: =isearch-forward=, =isearch-backward=, ends with a =RET=. After enter the search mode, =C-w= (=isearch-yank-word=or-char=), =M-s C-e= (=isearch-yank-line=), =C-y=, =M-y= and many isearch yanking commands yank text into the search minibuffer.

 To return to where the search starts (saved in the mark ring), =C-u C-SPC=. =C-s C-s=/=C-r C-r= starts the previous search again. =C-s M-n=/=C-s M-p= chooses from the search ring. =M-e= to enter the minibuffer to modify the search string.

* Major and Minor Modes

- *Major Mode*: specialized facilities for working on a specialized file type. Major modes are mutually exclusive.
  + Three groups:
    - Normal text, plain or markup
    - Various programming languages
    - special buffers such as shell, =Dired=, =Message=.
  + =C-h m= describes the current mode.
  + Each major mode defines a mode hook, a list of Lisp functions to run each time the mode is enabled in a buffer.

- *Minor Mode*: optional features not necessarily specific to a type of file or buffer.
  + Minor modes can be buffer-local or global.
  + Some useful minor modes:
    - =display-line-numbers=
    - visual line-mode.
    - line number mode, enabled by default
    - menu bar mode
    - scroll bar mode

Emacs determines the major mode by first finding a =; -*- mode: my-mode ;-*-= string in the buffer, then by =#!=, then by matching the start of the text, then matching the file name and finally falling back to another mode.

* Normal Text Editing

- =M-t=: =transpose-words=, exchange two words at both sides of the point.

- =M-a=, =M-e=, =M-k=, =C-x DEL=: sentence editing commands.

- Case conversion
  + =M-l=, =M-u=
  + =M-c=
  + =C-x C-l=, =C-x C-u=

- =M-{=, =M-}=, =M-h=: paragraph commands

- =auto-fill-mode=: automatically breaks the line at spaces when necessary (filling the text)
  + =M-q=: =fill-paragraph=
  + =C-x f=: set the fill column
  + =fill-region=
  + =M-o M-s= Center a line
