#+title: Org Mode
#+author: djndl1
#+OPTIONS: ^:{}
#+FILETAGS: :org:orgmode:org-mode:

* Rich Text

Paragraphs are separated by at least one empty line. A line break can be forced
with =\\=.

To write literal text

#+begin_verse
This paragraph should be
now complete literal.
#+end_verse

#+begin_quote
My Quote
#+end_quote

#+begin_center
Centered Text
#+end_center

#+begin_example
Example blocks are typeset in monospace.
#+end_example

=*=, =#+= must be prefixed with a =,= in the blocks above to avoid conflicts.
Example block and source code blocks can be used with a =-n= number switch.


=^= and =_= are used to indicate superscripts and subscripts (along with ={}=
as in LaTeX). These behaviors may get in the way. Use =OPTIONS: ^:{}= to limit
them only to the LaTeX-style notation or simply use LaTeX.

Special symbols can be inserted using LaTeX-like syntax. See [[elisp:org-entities-help][org-entities-help]].

=-----= is exported as a horizontal line.

** LaTeX

LaTex fragments can be inserted without special marking as long as they are
enclosed with =\begin= and =\end=. Inline math can be inserted with
=$=​/​=\(...\)= or =$$=​/​=\[...\]=.

\begin{equation}
a = b
\end{equation}

** Images

a link to an image file, probably with a caption and a name.

** Captions

Used with a table, a source block, an image and many others.

** Footnotes[fn:foo]

org-mode can have footnotes.

[fn:foo] https://orgmode.org/manual/Creating-Footnotes.html


* Layout and Structures
** Headlines

Headlines start with stars or indents combined with a single star.
=org-num-mode= displays outline numbering on top of headlines.

A headline named with =org-footnote-section= is treated as a subtree of footnotes.

#+begin_src org
,* Top level headline             |    * Top level headline
,** Second level                 |      * Second level
,*** Third level                |        * Third level
some text                  |          some text
**,* Third level                |        * Third level
more text                  |          more text
,* Another top level headline     |    * Another top level headline
#+end_src

#+RESULTS:
: * Top level headline             |    * Top level headline
: ** Second level                 |      * Second level
: *** Third level                |        * Third level
: some text                  |          some text
: **,* Third level                |        * Third level
: more text                  |          more text
: * Another top level headline     |    * Another top level headline

** Org Cycle (Folding)

- =org-cycle= :: rotate the current subtree among the states, can be used with =C-u=.

- =org-global-cycle=, =org-shifttab= :: rotate the entire buffer among the states

- =org-show-all= ::

- =org-reveal= ::

- =org-show-children= ::

- =org-move-item-up/down= ::

** Motion

- =org-next-visible-heading=, =org-previous-visible-heading= ::

- =org-forward-heading-same-level=, =org-backward-heading-same-level= ::

- =outline-up-heading= ::

- =org-goto= ::

** Editing

- =org-meta-return= :: the exact operation depends on the context

- =org-narrow-to-subtree= ::

- =org-copy-subtree=; =org-paste-subtree=, =org-cut-subtree=,  =org-mark-subtree=; =org-yank= ::

- =org-do-promote=, =org-do-demote=; =org-promote-subtree=,  =org-demote-subtree= ::

- =M-TAB= :: org-mode completion
  + TeX symbols
  + Tags, property after a =:=
  + After =#+=

- =org-insert-structure-template= :: insert block structures

- =C-c C-c= :: heavily-overloaded
  + realign tables
  + renumber the ordered list
  + toggle a checkbox
  + switch between a footnote reference and its definition
  

** Lists

Items belonging to the same list must have the same indentation on the first
line. An item ends before the next line that is less or equally indented than
its bullet/number. It also ends before two blank lines.
Indentation is what governs the structure of lists: blocks and text can be indented to indicate that they belong to a certain item.

** Drawers

Stores meta information or info that the author does not intend to store in the
main article.

** Sparse Trees

- =org-sparse-tree= :: selectively show certain trees.

* Tables

Org-mode has a built-in table editor.

A table is re-aligned automatically each time =TAB=, =RET= or =C-c C-c= is
pressed inside the table.

** Operations

- =org-table-create-or-convert-from-region= :: convert CSV text to a table or
  create a new one.

- =org-table-align= ::

- =org-table-blank-field= :: clear the field

- =org-table-move-left/right=, =org-table-beginning/end-of-field=,  =org-table-move-row-up/down= ::

- =org-table-delete/insert-column=, =org-table-kill/insert-row= ::

- =org-table-edit-field= :: edit the current field in a separate window

- =org-table-import/export= :: import/export CSV-like (tab mostly) files

- =org-table-toggle-column-width=, =org-table-shrink/expand= ::

- =/=, =<=, =>= :: group columns and show vertical lines

** Spreadsheet Calculations

The table editor makes use of the Emacs Calc package to implement
spreadsheet-like capabilities with elisp or =Calc= expressions.

*** References

- =@Row$Column= :: Field reference
  + may be absolute or relative

- =REF..REF= :: range reference

- =$name= :: named reference

- =remote(NAME, REF)= :: references in another table

** Plotting

Plot org tables graphically using Gnuplot or in ASCII art.

* Links
:PROPERTIES:
:CUSTOM_ID: links_section
:END:
#+NAME: LinkSection
<<links_target>>



#+begin_src org
[[LINK][DESCRIPTION]]
# or
[[LINK]]
#+end_src

=[=, =]=, at some =\= needs to be escaped. Use the =org-link-escape= function to
escape a link. Edit the link part with =org-insert-link=.

A link may be
  + /External Link/: [[https://orgmode.org/manual/External-Links.html][many schemes]] are supported.
  + /internal link/ that refers to [[*Links][somewhere in the current document]].
  [[*Links][Links Section]]
  [[#links_section][Links Section By ID]]
  [[links_target][Links by dedicated target]]
  [[LinkSection][Link Section by name]]

  Links are created for <<<radio targets>>>. See radio targets.

Link abbreviation can be defined with =+LINK:=.

- =org-store-link= :: save the current point as a link to a =org-stored-link= to
  be used later with =org-insert-link=.

- =org-mark-ring-push= ::

- =org-mark-ring-goto= :: go backup the a recorded position

- =org-open-at-point= :: open link at point

- =org-next/previous-link= ::

* Tags :tag:

Used to implement labels and contexts for cross-correlating information.
Tags occur at the end of the headlines.

Tags are inherited by subtrees by default.

- =org-set-tags-command= ::

A file can have tags by setting =#+FILETAGS:=.

Tags can be defined in hierarchies. A tag can be defined as a group tag for a
set of other tags.

** Search

- =org-match-sparse-tree= :: narrow to a sparse tree of headlines matching the
  tag

* Properties
:PROPERTIES:
:CUSTOM_ID: property_section
:END:

A key-value pair associated with an entry or the whole buffer. Used as a tag with a value or a
simple database.

Properties are inserted into a special drawer =:PROPERTIES:= located right below
a headline or =#+PROPERTY: propertyName propertyValue= with the whole buffer.

A property may or may be be inherited by its subtree depending on =org-use-property-inheritance=.
The allowed values of a property can be defined with =:propertyName_ALL: value1
value2 value3=. Use =propertyName+= to add values to an existing property.

** Search

- =org-match-sparse-tree= ::

- =org-sparse-tree= ::

** Editing

- =org-columns= ::

- =org-columns-quit= ::

* TODO Items

TODO items usually come up while taking notes.

** Dates and Times

The presence of a timestamp causes an entry to be shown on specific dates in the
agenda.

*** Timer

- =org-timer-start= :: a relative timer that counts up, possibly with an initial
  value.

- =org-timer-set-timer= :: start a countdown timer

** Refiling and Archiving

Information needs to be moved around.

- /refiling/ :: copy/cut some of the entries into a different list. The refiled item
  is placed below the target heading as a subitem.
  + =org-refile-targets= :: by default these targets are scanned.
  + =org-refile= :: cut-refile
  + =org-refile-copy= :: copy-refile
  + =org-refile-goto-last-stored= ::

- /archiving/ :: a finished subtree is moved into an archive file and is no longer in
  the agenda.
  + =#+ARCHIVE:= :: set the archive location
  + =org-archive-subtree= ::

** Scheduling and Deadlines

*** Repeated Tasks

A repeated =+duration= is added to the end of a timestamp. Multiple due tasks
are not marked done after one of them is done.

- =++duration= :: the next due date is always in the future.

- =.+duration= :: due based on the last time done.

** Org-Capture

The idea comes from GTD, basically a way to quickly capture and write down some
ideas on paper.

- =org-default-notes-file= ::

- =org-capture= ::

- =org-capture-refile= ::

- =org-capture-kill= :: abort the capture process

* Source Code (Org Babel)

Source code blocks can be edited, extracted, exported, published and even
compiled and executed. Emacs major modes are used for source code blocks.
Org mode can pass variables, functions and results to one another using a common
syntax.

Typing =<s= and then pressing =TAB= generates a source code block.

#+begin_src org
my org mode block
#+end_src

An inline code block goes with a structure src_elisp{(+ 1 3)}

* In-Buffer Settings

#+begin_src org
,#+CATEGORY:  # agenda file category
,#+CONSTANTS: n=v # define variables
,#+FILETAGS: :tag1:tag2:tag3: # file-local tags inherited by all entries
,#+PROPERTY: propName propValue # a default inheritance value for entries in the current buffer
,#+SETUPFILE: file # a URL or a path to a file for additional in-buffer settings
,#+STARTUP: #startup options
,#+TAGS: TAG1(c1) TAG2(c2) # tags available
#+end_src


* Include Files

#+begin_src org
#+INCLUDE: quoted_path_string [block_type] [source_code_lang]
#+end_src
