#+title: Org Mode
#+author: djndl1

* Layout and Structures

** Headlines

Headlines start with stars or indents combined with a single star. =org-num-mode= displays outline numbering on top of headlines.

#+begin_src org
,* Top level headline             |    * Top level headline
,** Second level                 |      * Second level
,*** Third level                |        * Third level
some text                  |          some text
**,* Third level                |        * Third level
more text                  |          more text
,* Another top level headline     |    * Another top level headline
#+end_src

** Org Cycle (Folding)

- =org-cycle= :: rotate current subtree among the states

- =org-global-cycle= :: rotate the entire buffer among the states

- =org-show-all= ::

- =org-reveal= ::

- =org-show-children= ::

** Motion

- =org-next-visible-heading=, =org-previous-visible-heading= ::

- =org-forward-heading-same-level=, =org-backward-heading-same-level= ::

- =outline-up-heading= ::

- =org-goto= ::

** Editing

- =org-meta-return= :: the exact operation depends on the context

- =org-narrow-to-subtree= ::

- =org-copy-subtree=; =org-paste-subtree=, =org-cut-subtree=,  =org-mark-subtree=; =org-yank= ::

- =org-do-promote=, =org-do-demote=; =org-promote-subtree=, =org-demote-subtree=  ::

** Lists

Items belonging to the same list must have the same indentation on the first
line. An item ends before the next line that is less or equally indented than
its bullet/number. It also ends before two blank lines.
Indentation is what governs the structure of lists: blocks and text can be indented to indicate that they belong to a certain item.

** Drawers

Stores meta information or info that the author does not intend to store in the
main article.

** Sparse Trees

- =org-sparse-tree= :: selectively show certain trees.

* Tables

Org-mode has a built-in table editor.

A table is re-aligned automatically each time =TAB=, =RET= or =C-c C-c= is
pressed inside the table.

** Operations

- =org-table-create-or-convert-from-region= :: convert CSV text to a table or
  create a new one.

- =org-table-align= ::

- =org-table-blank-field= :: clear the field

- =org-table-move-left/right=, =org-table-beginning/end-of-field=,  =org-table-move-row-up/down= ::

- =org-table-delete/insert-column=, =org-table-kill/insert-row= ::

- =org-table-edit-field= :: edit the current field in a separate window

- =org-table-import/export= :: import/export CSV-like (tab mostly) files

- =org-table-toggle-column-width=, =org-table-shrink/expand= ::

- =/=, =<=, =>= :: group columns and show vertical lines

** Spreadsheet Calculations

The table editor makes use of the Emacs Calc package to implement
spreadsheet-like capabilities with elisp or =Calc= expressions.

*** References

- =@Row$Column= :: Field reference
  + may be absolute or relative

- =REF..REF= :: range reference

- =$name= :: named reference

- =remote(NAME, REF)= :: references in another table

** Plotting

Plot org tables graphically using Gnuplot or in ASCII art.

* Links
#+NAME: LinkSection
:PROPERTIES:
:CUSTOM_ID: links_section
:END:
<<links_target>>



#+begin_src org
[[LINK][DESCRIPTION]]
# or
[[LINK]]
#+end_src

=[=, =]=, at some =\= needs to be escaped. Use the =org-link-escape= function to
escape a link. Edit the link part with =org-insert-link=.

A link may be
  + /External Link/: [[https://orgmode.org/manual/External-Links.html][many schemes]] are supported.
  + /internal link/ that refers to [[*Links][somewhere in the current document]].
  [[*Links][Links Section]]
  [[#links_section][Links Section By ID]]
  [[links_target][Links by dedicated target]]
  [[LinkSection][Link Section by name]]

  Links are created for <<<radio targets>>>. See radio targets.

Link abbreviation can be defined with =+LINK:=.

- =org-store-link= :: save the current point as a link to a =org-stored-link= to
  be used later with =org-insert-link=.

- =org-mark-ring-push= ::

- =org-mark-ring-goto= :: go backup the a recorded position

- =org-open-at-point= :: open link at point

- =org-next/previous-link= ::
