* Echo

Besides =echo=, there  is =echom= that echo into the =:messages= buffer.

* Vimscripts


To execute a copied block of vimscript, use =:@=. 
To execute a selected region, use =(vim9) so= in command mode.

- conditions are not required to be surrounded by parentheses.

- =elseif=, not =else if=; =if= ends with an =endif=

- =let= assigns a variable.
  + a variable may has a prefix to indicate its scope:
    - =a=: function argument
    - =b=: buffer-local
    - =g=: global
    - =l=: function-local
    - =s=: script-level
    - =t=: tab-level
    - =v=: controlled by Vim
    - =w=: window-level
  + by default variables are global =g=, Vimscript9 solves this with a
    dedicated =var= keyword to declare a local variable.
  + =:let= without arguments lists global variables 

- =unlet=: delete variable and its related objects.

- ~==~ on strings is affected by =ignorecase= and should not be used for string comparison.
  + use ~==?~ and ~==#~ for case-insensitive and case-sensitive comparison.

- =.= string concatenation
  + (Vim9script): =..= 

- =execute=: execute a string as vimscript

#+begin_src vim
let g:Favcolorschemes = ["darkblue", "morning", "shine", "evening"]
function SetTimeOfDayColors()
    " currentHour will be 0, 1, 2, or 3
    let g:CurrentHour = strftime("%H") / 6
    if g:colors_name !~ g:Favcolorschemes[g:CurrentHour]
    execute "colorscheme " . g:Favcolorschemes[g:CurrentHour]
    echo "execute " "colorscheme " . g:Favcolorschemes[g:CurrentHour]
    redraw
    endif
endfunction
#+end_src

- to execute a function in command mode, =:call funcname()=

- Arrays/Lists: =[elm1, elm2, elm3, elm4, ...]
  + =for n in lst=

- Python-like tuple

- Python-like Dictionaries

- Line continuation =\= before (not after) a line 
  + Vim9script eliminates some use of =\=

- =&option_name=: retrieve the vale of an option

Vim uses /events/ to execute commands (/autocommands/) e.g. =BufNewFile=, =BufReadPre=, =BufRead=,
=BufReadPost=, =BufWrite=, =BufWritePre=, =FileType=, =VimResized=, =WinEnter=,
=WinLeave=, =CursorMoved=, =CursorMovedI=.

#+begin_src vim
augroup newFileDetection
# everytime the cursor moved under Insert mode.
    autocmd CursorMovedI * call CheckFileType()
augroup END

function CheckFileType()
    if exists("b:countCheck") == 0
        let b:countCheck = 0
    endif
        let b:countCheck += 1
    " Don't start detecting until approx. 20 chars.
    if &filetype == "" && b:countCheck > 20 && b:countCheck < 200
        filetype detect
    elseif b:countCheck >= 200 || &filetype != ""
        autocmd! newFileDetection # delete the commands within the group, deleting a group doesn't delete its commands.
    endif
endfunction
#+end_src

- to execute a script, run =source scriptfile=.

** Vim9script

Vim9script is strongly-typed.

#+begin_src vimscript
vim9script

# local variable
var variable_name = value
var typed_string: string = "String_value" 
# string may be double quoted now, the rule is similar to that of Unix shell
# global variable
g:global_variable_name = value
while condition
      loop_body # continue, break are supported
endwhile

# there's even interpolated string
var s = $"name: {name}"
# coalesce operator
echo name ?? "No name given"

for v in range(1, 4)
      loop_body
endfor

def {name)(params_list): return-type
      function_body
enddef
#+end_src

