#+title: Physical Layer

* Guided Transmission Media

** Persistent Storage

#+begin_quote
Never underestimate the bandwidth of a station wagon full of tapes hurtling
down the highway.
#+end_quote

e.g. snowmobile service (a truck of hard disks that is able to connect to a fiber network)

** Twisted Pair

Two insulated copper wires twisted together in a helical form to cancel out
waves. A signal is usually carried as the difference in voltage between the two.
Twisted pairs can run several kilometers without amplification. They may be used
for analog or digital signal. The bandwidth depends on the thickness of the
wire, easily reaches hundreds of Mbps for a few kilometers.

e.g. telephone, ADSL internet access

Twisted pairs typically have four pairs in a cable. Different LAN standards use
the twisted pairs differently, some with more pairs while some fewer.

Twisted pair cables are categorized. Category 5 can support 100-Mbps and 1Gbps LAN.
Category 6 can support up to 10Gbps. Category 7 introduced shielding on the
individual twisted pairs and the entire cable. Category 8 runs at higher speeds
but over a shorter distance.

** Coaxial Cable

A stiff copper wire as the core, surrounded by an insulating material and then
enveloped by a cylindrical conductor, often as a closely woven braided mesh. The
outer surface is a protective plastic sheath.

- High bandwidth up to 6 GHz.

- Used as long distance lines. Still widely used for cable television and
  metropolitan area networks.

** Power Lines

An old idea for remote metering, but a new idea for high-rate communications.

Difficulties: quick to attenuate; constant change of the electrical properties
due to the change of electric use; transient currents and noise caused by
switching on/off of appliances; the wiring itself is susceptible to external noise.

** Fibers

Up to 50 Tbps, fast but expensive at the edge to the point where computation
resource and cache storage are used.

An optical transmission system has three key components: *the light source*
(LEDs or semiconductor lasers),
*the transmission medium (an ultra-thin fiber of glass*), *the detector* (photodiode). A
light source is attached to one end and the detector at the other end to receive
the light signal.
A pulse of light indicates 1 bit and the absence of light indicates 0 bit.

A light ray incident on the boundary of two media at or above the critical angle
is fully reflected back into the original medium and can propagate for
kilometers with virtually no loss.

Each ray is said to have a different *mode*. A fiber that has multiple rays
reflected at different angles are called a *multimode fiber*. A fiber less than
10 microns can propagate light only in a straight line without bouncing,
yielding a *single-mode fiber* (for long distance about 50 times farther than
multimode fibers, up to 100 Gbps for 100 km without amplification).

The attenuation of light within a fiber depends on the wavelength. Three
wavelength bands (0.85, 1.30 and 1.55 micros) are most commonly used.

A fiber has a glass core, where light is trapped inside, and wrapped by a
glass cladding with a lower index of refraction, and then a plastic jacket.
Multiple fibers grouped in a cable.

Fibers can be mechanically spliced together in about 5 minutes for trained
personnel and result in a 10% light loss, fused to form a solid connection
without much light loss or terminate in conenctors and be plugged into fiber sockets.

* Wireless Transmission

** The Electromagnetic Spectrum

 Radio, microwave, infrared, visible light can all be used for information
 transmission. High-frequency UV, X-ray and Gamma ray are even better but they
 are difficult to produce and modulate, do not propagate well through buildings
 and they are harmful to living things.

 The amount of information that a signal such as electromagnetic wave can carry
 depends on the received power and is proportional to its bandwidth. Most
 transmissions use a relatively narrow frequency band.

*** Spread Spectrum

#+TODO: more clarification

#+begin_quote
spread spectrum are techniques by which a signal (e.g., an electrical,
electromagnetic, or acoustic) generated with a particular bandwidth is
deliberately spread in the frequency domain over a wider frequency band.
Spread-spectrum techniques are used for the establishment of secure
communications, increasing resistance to natural interference, noise, and
jamming, to prevent detection, to limit power flux density (e.g., in satellite
downlinks), and to enable multiple-access communications.
#+end_quote

 - *Frequency Hopping Spread Spectrum* :: a transmitter hops from frequency to
   frequency hundreds of times per second.
   + Hard to detect and jam
   + well resistant to multipath fading
   + suitable for crowded channels.
   + e.g. bluetooth, older versions of 802.11

- *Direct Sequence Spread Spectrum* :: uses a code sequence to spread the data
  signal over a wide frequency band.
  + e.g. GPS, 3G mobile networks,

- *Ultra-Wideband Communication* :: a series of low-energy rapid pulses that
  varying their carrier frequencies over a very wide frequency band.
  + at least 500MHz wide
  + tolerable to a substantial amount of relatively strong interference from
    other narrowband signals.
  + little interference to other narrowband signals.

** Electromagnetic Information Transmission

*** Radio (Frequency) Transmission

Around 20kHz to around 300MHz

RF is easy to generate, can travels long distances, penetrates buildings easily.
Radio waves are omnidirectional: antennas need not be precisely aligned.

Radio waves are subject to path loss — signal energy loss as fast as $1/r_{2}$
in the air. Low-frequency waves pass through obstacles well but suffer path loss
sharply. High-frequency waves reflect upon obstacles and can be absorbed by rain
and other obstacles. VLF, LF and MF waves follow the ground; HF and VHF tend to
be absorbed by the earth but reflect off the ionosphere.

*** Microwave Transmission

Between 300 Mhz and 300 GHz

Cheap directional long-distance transmission in a straight line.
It offers high signal-to-noise ratio due to concentrated energy.
It suffers from multipath fading and absorption by rain.

*** Infrared Transmission

Relatively directional, cheap and easy to build.
Unable to pass through solid objects.

Not a major communication method.

*** Light Transmission

Unguided optical signaling is inherently unidirectional, offers very high
bandwidth at very low cost and is easy to install.

It is difficult to align the transmitter and the receiver and the beam is susceptible to
temperature change and bad weather.
